### ISSUE TITLE
Quest ID 11067 Dragonmaw Race: Trope the Filth-Belcher

### ISSUE THREAD

**Issue by MirNelthDB** [gamefreedomgit/Maelstrom#6097] opened 2024-08-23 20:21 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Behaviour is like #6089 just now NPC ID 23342 Trope the filth belcher disapear. 

 NPC ID 22433 Jay Nosliw isnt on a correct position in the village.

**How to reproduce:**

**How it should work:**
https://www.youtube.com/watch?v=LD96W58e5KU

**Database links:**
https://www.wowhead.com/quest=11067/dragonmaw-race-trope-the-filth-belcher
https://www.wowhead.com/npc=23342/trope-the-filth-belcher

**Comment by Sketish** [comment] 2024-08-23 20:56
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6089

**Closed by Sketish** 2024-08-23 20:56 UTC
