### ISSUE TITLE
bug bag

### ISSUE THREAD

**Issue by chamanisimo** [gamefreedomgit/Maelstrom#3629] opened 2023-05-26 20:45 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Today I bought a bag at the gadgetsam auction house, but when I put it on, nothing comes out, it's like it's binded to someone else 
**How to reproduce:**

**How it should work:**

fix the problem or give me back the gold

**Database links:**

**Comment by Sketish** [comment] 2023-06-01 12:48
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/3576

**Closed by Sketish** 2023-06-01 12:48 UTC
