### ISSUE TITLE
Throne of the Tides [Dungeon] Deathwing kill us

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1099] opened 2022-12-12 18:51 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Deathwing is everywhere, even in the dungeon
![image](https://user-images.githubusercontent.com/120294125/207129585-2034c15b-e4d3-464a-a1f4-d6c0af08347a.png)
![image](https://user-images.githubusercontent.com/120294125/207129624-aebc9af1-06c2-4990-a040-9912e509a678.png)

**How to reproduce:**

**How it should work:**

**Database links:**

![image](https://user-images.githubusercontent.com/120294125/207129502-e5b3fba1-7070-43ed-a99e-523ec13495cb.png)

**Comment by UltraNix** [comment] 2022-12-12 21:54
Duplicate of #1087

**Closed by UltraNix** 2022-12-12 21:54 UTC
