### ISSUE TITLE
Silverpine Quest Bugged - Skitterweb Matriarch

### ISSUE THREAD

**Issue by Voltarious** [gamefreedomgit/Maelstrom#4653] opened 2023-09-30 20:50 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/quest=27094/deeper-into-darkness)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The quest Deeper Into Darkness, located in The Skittering Dark-Silverpine Forest, is bugged. You need to kill Skitterweb Matriarch, but the mob is untargetable and unkillable. The quest leads into the next zone quest, so without it, you can't continue the zone. 

**How to reproduce:**

**How it should work:**
The mob should be able to be killed for quest completion.

**Database links:**
https://www.wowhead.com/quest=27094/deeper-into-darkness

**Comment by Sketish** [comment] 2023-10-01 08:18
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4365

**Closed by Sketish** 2023-10-01 08:18 UTC
