### ISSUE TITLE
onyxia

### ISSUE THREAD

**Issue by xmrshoot** [gamefreedomgit/Maelstrom#3820] opened 2023-06-13 18:37 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Pls despawn onyxia after she is dead we cant see portals well its annoying

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment] 2023-06-13 20:05
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/3732

**Closed by Sketish** 2023-06-13 20:05 UTC
