### ISSUE TITLE
[Rogue] Poison damage in assasination

### ISSUE THREAD

**Issue by beatkrokfreety** [gamefreedomgit/Maelstrom#1972] opened 2023-01-19 10:15 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Poison mastery in assassination doesn't work. Does very low amount of damage and probably low chance of procs even under envenom buff.
![image](https://media.discordapp.net/attachments/767044410117455877/1065573456479014942/image.png)
![image](https://media.discordapp.net/attachments/767044410117455877/1065573455711457300/image3.png)
![image](https://media.discordapp.net/attachments/767044410117455877/1065573455443013662/image4.png)
![image](https://user-images.githubusercontent.com/36668875/213414858-b47b01bd-3e9a-4882-ac1c-cde183d93cd0.png)
![image](https://user-images.githubusercontent.com/36668875/213415060-7e685f74-916a-492d-83ce-0e0be89c0d02.png)

**How to reproduce:**
Can check it any dummy or wherever.

**How it should work:**
Instant poison and deadly should do much more damage than mutilate autoatack etc.

**Database links:**

**Comment by MullichWhitemane** [comment] 2023-01-20 05:06
There is no such thing as "Poison Mastery" anywhere on Assassination Rogue. Not in your screenshots, and not anywhere that I can see in game. Can you please explain your issue again so I can validate this?

I am also wondering how you managed to get Instant Poison to damage your target, as currently, it heals any target struck by 1. https://github.com/gamefreedomgit/Maelstrom/issues/1964 for reference.

**Comment by beatkrokfreety** [comment] 2023-01-21 07:04
There is random log from apollo
https://www.warcraftlogs.com/reports/XRGyT8jDQFd4qgwv#fight=73&type=damage-done&source=236

**Comment by MullichWhitemane** [comment] 2023-01-21 15:53
> There is random log from apollo https://www.warcraftlogs.com/reports/XRGyT8jDQFd4qgwv#fight=73&type=damage-done&source=236

This is still insanely low info but I will dig into this then. There are already documented issues with Assassination Rogue that are breaking the spec, but if I might point out:

> Instant poison and deadly should do much more damage than mutilate autoatack etc.

In the logs you have given, Deadly Poison barely overtook Mutilate damage, and that is because of Backstab usage.

**Comment by MullichWhitemane** [comment] 2023-01-21 16:20
I have run some tests, and everything other than the bugs reported in https://github.com/gamefreedomgit/Maelstrom/issues/1964 works.
Agility and attack power scalings work.
Potent Poisons work.
Lethality and Coup de Grace work.
Vile Poisons work.
Master Poisoner works.

Unless you provide me new evidence @beatkrokfreety I will be closing this page in the next 24 hours.

**Comment by beatkrokfreety** [comment] 2023-01-21 21:10
2.7mil instant poison damage against 550k instant poison damage with the practically same value of aa? Isn't there something strange here?
Probably you should check procs of deadly poison when it stacks 5. It says if u have 5 stack deadly when u poison again u proc poison from other weapon.

**Comment by MullichWhitemane** [comment] 2023-01-22 02:48
Okay, I have checked - Deadly Poison actually works as intended, it procs your other weapon's poison just fine, the issue mentioned in https://github.com/gamefreedomgit/Maelstrom/issues/1964 is related to non Deadly Poison procced posions, which is where the massive amounts of missing damage come in from.
![instant d poison](https://user-images.githubusercontent.com/121984461/213898219-c8bda1c7-5dd2-478b-8bdd-df19b1e5c7e6.PNG)
As you can see in this combat log, my normal weapon procced Instant Poison will heal the Dummy by one on proc, but the Deadly Poison procced Instant Poison will do damage as normal.

As this issue is already reported in https://github.com/gamefreedomgit/Maelstrom/issues/1964 I will be closing this post.

**Closed by MullichWhitemane** 2023-01-22 02:48 UTC
Labels: Class: Rogue, Status: Need Info
