### ISSUE TITLE
Redirect not working 

### ISSUE THREAD

**Issue by Kyze777** [gamefreedomgit/Maelstrom#3615] opened 2023-05-25 13:42 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Redirect does not transfer combo points from target A to target B and goes on CD

**How to reproduce:**
Build combo points on one Target (A) > Select another Target (B) > Use Redirect > Doesn't transfer CP 

**How it should work:**
The amount of CP built on Target A should transfer to Target B 

**Database links:**

**Comment by Sketish** [comment] 2023-05-25 17:39
duplicate off https://github.com/gamefreedomgit/Maelstrom/issues/3614

**Closed by Sketish** 2023-05-25 17:39 UTC
