### ISSUE TITLE
[Scarlet Monastery Library] Mobs fall through ground

### ISSUE THREAD

**Issue by apostolovskisimon** [gamefreedomgit/Maelstrom#2699] opened 2023-03-28 09:18 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mobs fall through the ground, ranged dps can still dps them but no loot. Its not doable

**How to reproduce:**
Enter Library, go pull mobs

**How it should work:**
Mobs shouldn't fall through ground

**Database links:**

**Comment by Waroxx-QA** [comment] 2023-03-28 12:46
Can't reproduce it, i pulled the whole dungeon, no mob fell undermap
Can you give us more details ?

**Comment by jpaardekooper** [comment] 2023-03-31 08:29
They are already spawned under the map.

**Comment by Waroxx-QA** [comment] 2023-04-02 01:39
> They are already spawned under the map.
Can you make a screenshot or smthng  ? i coudn't find em

**Comment by UltraNix** [comment] 2023-06-17 11:04
No further info - closing.

**Closed by UltraNix** 2023-06-17 11:04 UTC
Labels: Status: Need Info
