### ISSUE TITLE
Eclipse for Boomy

### ISSUE THREAD

**Issue by Jajaboomy** [gamefreedomgit/Maelstrom#2787] opened 2023-04-01 22:41 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I don't know if it's already reported, but sometimes, you are stuck in Eclipse. You can just cast spells again and again and it doesn't change anything. Kinda annoying for mana, and haste proc.

**How to reproduce:**

**How it should work:**
When you have Eclipse, you cast spells until you go to 0, then swap eclipse.

**Database links:**

**Comment by Waroxx-QA** [comment] 2023-04-02 00:33
Proof and/or more informations are needed for these kind of reports. we can't waste our time trying to reproduce something that we can't reproduce mostly, that's why video proof or a step-by-step explaination so we can make it happen 100%, then we can fix it !

**Comment by UltraNix** [comment] 2023-05-30 11:05
No further info - closing.

**Closed by UltraNix** 2023-05-30 11:05 UTC
Labels: Class: Druid, Status: Need Info
