### ISSUE TITLE
Bug "Master of the Molten Flow" - Kill a Flamewaker Shaman with his own Flamewave

### ISSUE THREAD

**Issue by Jebuslas** [gamefreedomgit/Maelstrom#6152] opened 2024-09-14 05:55 UTC
**Description:** Although I killed the Flamewaker shaman with his own flame wave ability, it does not count towards the achievement.

![1](https://github.com/user-attachments/assets/b01a40da-d03b-41c6-9df8-38dc2ff0e40b)
![2](https://github.com/user-attachments/assets/d7f699d4-30a2-477f-b7ff-3ff48e5e5af9)

**Database links:**
https://www.wowhead.com/achievement=5871/master-of-the-molten-flow

**Comment by Sketish** [comment] 2024-09-14 08:42
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6149

**Closed by Sketish** 2024-09-14 08:42 UTC

**Comment by PanJanuszek** [comment] 2024-09-14 18:46
Fix **_is not_** on repo as I mentioned in other ticket
