### ISSUE TITLE
faerie fire breaks sap

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4411] opened 2023-09-03 22:47 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
human form faerie fire is breaking sap at the moment

**How to reproduce:**
sap a target then have your friend faerie fire it

**How it should work:**
it shouldnt break sap cause it does 0 dmg?

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=770

**Comment by UltraNix** [comment] 2023-09-27 13:17
@SimonBpvp I can't reproduce it. Can you record it?

**Comment by UltraNix** [comment] 2023-11-09 15:26
No further info - closing.

**Closed by UltraNix** 2023-11-09 15:26 UTC
Labels: Class: Druid, Class: Rogue, Status: Need Info, PVP: Mechanic
