### ISSUE TITLE
[Moved from Discord]  Gargoyle and Spirit wolves following rogues who vanished

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#2182] opened 2023-02-19 23:45 UTC
Description: When vsing a Death knight as a rogue, if the DK uses gargoyle and the rogue vanishes or stealths the gargoyle will follow the rogue in stealth.

How to reproduce: duel a death knight as rogue, have him pop gargoyle and vanish when near the gargoyle.

How it should work: The gargoyle should lose sight of the rogue.

Confirmed this is also applicable to Spirit Wolves from Shamans

**Comment by ussj10** [comment] 2023-02-20 01:38
Seen the shaman cases on last stream but unfortunately it's very hard to reproduce. Most of the times rogue vanishes on my wolves, they just stood doing nothing. I thought it may be tied to applying a debuff like Gargoyle does, since Spirit Wolves have an aoe taunt ability. However from 2 cases I can recall from the tournament, only one of them included using that taunt.

**Comment by MrTide** [comment] 2023-02-21 20:58
Please also take a look to their damage calculation, i believe foster already talked to you about the issues with you unless you need more info.

**Comment by ussj10** [comment] 2023-02-21 22:28
[https://www.youtube.com/watch?v=rZo2J2OQsxg](url)
For anybody trying to calculate Wolves damage - here is a clip that shows shaman's exact attack power as well as shows rough inspections of targets so all dmg and reductions can be almost perfectly replicated and compared (keep in mind things like shadowform, shaman not using any burst cds/procs to buff them and whether mage/priest had some absorb atm). The only unknwon is whether they are glyphed (I say he did not use it) but it makes enough of a difference to be easily spotted.

I was unable to find any patch notes changing anything about them, so there shouldn't be any unaccounted for inconsistency between patch 4.0.6 from the clip and classes from patch 4.3 on PTR.

I'm not sure whether they should or shouldn't have the shaman's AP buff (even if shaman doesn't spec into it - they still get it from blood dk, mm hunt etc.). I can't really find any clip where they have this buff but then again it's very UI dependent.

**Comment by UltraNix** [comment] 2023-02-23 15:37
I can't reproduce this with Spirit Wolves.

**Comment by WhitemaneSylah** [comment] 2023-02-23 16:38
https://www.youtube.com/watch?v=QwG1f9QR8gg
https://www.youtube.com/watch?v=nGb8ESEwM6s
https://www.youtube.com/watch?v=9Tht25diBVg

@UltraNix  Garg examples,  do you want this done for spiritwolves too?

**Comment by UltraNix** [comment] 2023-02-23 16:47
@WhitemaneSylah Yes, please.

**Comment by WhitemaneSylah** [comment] 2023-02-23 17:24
https://www.youtube.com/watch?v=7lFD7kQE0ro
https://www.youtube.com/watch?v=Ooh05Qy0c8w

Here you go @UltraNix

**Comment by ussj10** [comment] 2023-02-23 20:13
@WhitemaneSylah 
The only cases where Wolves/Garg continued attacking were eye and vanishing 1 cm from enemy's face.
Eye makes you able to use all abilities on that enemy, so /petattack wouldn't be any different.
As for Rogue Vanishing on top of you - Vanish makes stealth unbreakable but not undetectable (mage's Invi is the only spell that makes you invisible no matter how close you get), hence you simply are not invisible to the pet owner. I've never seen or heard about a case where you're visible to pet owner and invisible to their pet at the same time.
So on all those 5 clips it seems to me that it's working correctly.

**Comment by sassouiabd** [comment] 2023-02-25 16:52
Have the fix been merged for this issue because its still reproductible on the PTR.
The Garg dk pet still follow a rogue after a vanish

**Comment by MullichWhitemane** [comment] 2023-02-25 18:28
> Have the fix been merged for this issue because its still reproductible on the PTR. The Garg dk pet still follow a rogue after a vanish

Can you please provide any video footage of this? I've attempted recreating the issue after the fix has been deployed in a variety of situations and other than in the intended scenarios (such as Vanishing right on top of a DK while Gargolye is up) the Gargolye always behaved normally.

**Comment by sassouiabd** [comment] 2023-02-25 18:45
Yes
https://www.twitch.tv/videos/1748937935
The expect behavior in this situation is :
The DK pet should lose the target after a vanish and stop following a rogue.

**Comment by MullichWhitemane** [comment] 2023-02-26 11:53
After narrowing it down, the Ghoul is the root of the issue. I managed to recreate it following your exact steps: DoTting up, doing damage, sending in the Ghoul, summoning the Gargoyle, etc etc. It seems that while the Ghoul and Gargoyle are attacking, only Ghoul understands that the Rogue Vanished. If it is only the Gargoyle attacking, he will understand Vanish as well.
https://www.youtube.com/watch?v=tTvKYGnGIN4
Here you can see the behaviour. I will be reopening this issue. Note that this issue no longer exists for Spirit Wolves.

**Comment by UltraNix** [comment] 2023-03-09 16:05
@MullichWhitemane Do you know if it still happenning?

**Comment by MullichWhitemane** [comment] 2023-03-10 00:57
@UltraNix I am not aware if they do - I've received no reports from players nor heard any complaints in most public channels. As the PTR is not up, I can't test - I know Gaga attempted a fix.

**Comment by MullichWhitemane** [comment] 2023-03-10 18:46
@UltraNix Tested now on the PTR - it does.

**Comment by UltraNix** [comment] 2023-03-10 19:26
Okay.

**Comment by UltraNix** [comment] 2023-03-15 10:01
Fixed.

**Closed by UltraNix** 2023-03-15 10:01 UTC
Labels: Class: Death Knight, Class: Shaman, Spell, PVP, Talent, Priority: High, Status: Confirmed, Bug Report from Discord
