### ISSUE TITLE
Honor wands giving 1-3 Maelstrom Crystals after disenchanting instead of 1, ruins the maelstrom crystal and enchants economy

### ISSUE THREAD

**Issue by markosoca** [gamefreedomgit/Maelstrom#4914] opened 2023-10-30 12:26 UTC
**Description:**
Honor wands disenchant for 1-3 maelstrom crystals instead of intended 1, relics for example which are also 700 honor disenchant correctly for 1 maelstrom crystal each, and so do the offhands that cost 950 honor.

**How to reproduce:**
Just buy a wand for 700 honor at the pvp honor vendor and disenchant (requires 475 Enchanting)

**How it should work:**
It should always disenchant for 1 Maelstrom Crystal EACH

**Database links:**
https://cata-twinhead.twinstar.cz/?item=61351
https://cata-twinhead.twinstar.cz/?item=61350

**Comment by xmrshoot** [comment] 2023-10-30 12:58
its not a bug

**Comment by markosoca** [comment] 2023-10-30 13:06
> its not a bug

your source?

**Comment by xmrshoot** [comment] 2023-10-30 13:19
https://www.wowhead.com/item=61351/vicious-gladiators-baton-of-light#disenchanting is should give 1 or 2 not only 1

**Comment by markosoca** [comment] 2023-10-30 13:24
cant open wowhead

> https://www.wowhead.com/item=61351/vicious-gladiators-baton-of-light#disenchanting is should give 1 or 2 not only 1

cant open wowhead blocked in my country, anyway it gives 3

**Comment by xmrshoot** [comment] 2023-10-30 14:18
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/4ce7aff6-75e0-4dc3-b426-f8be928be018)
 ye , so isnt bug , close it

**Comment by markosoca** [comment] 2023-10-30 14:41
> ![image](https://user-images.githubusercontent.com/129559513/279086255-4ce7aff6-75e0-4dc3-b426-f8be928be018.png) ye , so isnt bug , close it

no because this only happens for wands, all other honor gear NEVER give more then 1 maelstrom crystal

**Comment by markosoca** [comment] 2023-10-30 14:47
stop defending this shit just because youre abusing it, its not working correctly,

**Comment by markosoca** [comment] 2023-10-30 15:10
> It's not bug
> 
> actually when disenchanted 2-3 it is because of one of the benefits of the Guild lvl15-25 check and you will see that I was not wrong

show me a screenshot of u getting 3 maelstrom crystals from anything other then wand

**Comment by markosoca** [comment] 2023-10-30 15:11
i have disenchanted over 40 Relics now and i have never gotten more then 1 maelstrom crystal per relic, i also tried dozens of offhands too, only thing that gives more then 1 maelstrom crystals are the wands, if they are supposed to drop 2-3 then other gear like relics should too

**Comment by xmrshoot** [comment] 2023-10-30 15:16
![image](https://github.com/gamefreedomgit/Maelstrom/assets/129559513/753e290d-1872-4cab-a90b-6eb5c7cd02a6)
ye, its not bug , close it

**Comment by markosoca** [comment] 2023-10-30 15:26
> ![image](https://user-images.githubusercontent.com/129559513/279106064-753e290d-1872-4cab-a90b-6eb5c7cd02a6.png) ye, its not bug , close it

can you not spam

**Comment by xmrshoot** [comment] 2023-10-30 15:29
stop fucking cry , im not abusing i diont care about 80g crystal wtf go cry elsewhere

**Comment by xmrshoot** [comment] 2023-10-30 15:29
its not a bug , stop opening useless threads here

**Comment by xmrshoot** [comment] 2023-10-30 15:33
fuck your crystal idiot kid , go delete the game i dont give a fuck to your crystals

**Comment by markosoca** [comment] 2023-10-30 15:33
either wands should give less maelstrom crystals, or relics and other weapons should also be able to drop 2-3 its simple :)

**Comment by xmrshoot** [comment] 2023-10-30 15:33
i send you link it sayd gives 1-2 crystals and with guild perk the number increase but u are too dumb to understand

**Comment by markosoca** [comment] 2023-10-30 15:35
youre 

> i send you link it sayd gives 1-2 crystals and with guild perk the number increase but u are too dumb to understand

youre literally too stupid to understand what im saying XD, explain to me then why that guild perk only works on wands?

**Comment by xmrshoot** [comment] 2023-10-30 15:37
i dont care , i ignore u from now , fuck your maelstroms

**Comment by Revly** [comment] 2023-10-30 18:04
> > It's not bug
> > actually when disenchanted 2-3 it is because of one of the benefits of the Guild lvl15-25 check and you will see that I was not wrong
> 
> show me a screenshot of u getting 3 maelstrom crystals from anything other then wand

It is probability, if I have obtained 3 crystals (epic) (rare) & (commun) regardless, if it is a wand or another object.

I don't have SS

**Comment by markosoca** [comment] 2023-11-01 13:10
i would like to also add, it works like this for thrown weapons too, they give the same ammount as wands, other weapons like two handers give 1 max and never more then that

**Comment by UltraNix** [comment] 2023-11-01 17:01
Fixed.

**Closed by UltraNix** 2023-11-01 17:01 UTC
Labels: Loot, Profession: Enchanting
