### ISSUE TITLE
[QUEST] The mist Isn't Listening - BUG

### ISSUE THREAD

**Issue by Richi95cv** [gamefreedomgit/Maelstrom#4529] opened 2023-09-15 09:21 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Quest: The Mist Isn't Listening is bugged, mobs are unkillable and u cant finish quest chain. 

**How to reproduce:**

**How it should work:**
Mobs should be killable

**Database links:**

**Comment by Zeehra** [comment] 2023-09-15 14:12
Reported this ages ago, was closed at though it had been fixed, but I guess not. 

https://github.com/gamefreedomgit/Maelstrom/issues/2654

**Comment by UltraNix** [comment] 2023-09-16 13:31
Duplicate of #2031

**Closed by UltraNix** 2023-09-16 13:31 UTC
