### ISSUE TITLE
Nefarian climbing wall

### ISSUE THREAD

**Issue by Bandigoated** [gamefreedomgit/Maelstrom#3458] opened 2023-05-14 08:44 UTC
**Description:**
BWD 10 normal Nefarian fight. Phase 3. The maintank brought Nefarian to a wall (underneath the platform where players jump off), the tank were hugging the wall, then he rotated the boss like 45° to the right. Nefarian started to climbing up, like taking steps. Like every one-three seconds he "takes a step". After a while melee cant hit him. The only way to bring him down is to move him into the middle, then he climbs back down. 

Here is a picture to prove it: https://imgur.com/a/JZBOR7R

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment] 2023-05-14 15:35
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/3443

**Closed by Sketish** 2023-05-14 15:35 UTC
