### ISSUE TITLE
Guild heirloom transmogging price

### ISSUE THREAD

**Issue by valentnt** [gamefreedomgit/Maelstrom#3875] opened 2023-06-22 02:33 UTC
When trying to transmog the guild heirlooms (ones that scale up to lvl 85) it asks you for 375 gold to transmog it (which is exactly the selling price of the item) i have tried it with pants, maybe cloak is a little bit less since the selling price might be lower. The other heriloom parts (ones that scale up to lvl 80) are transmoggable for only 1g, should be fixed asap

**Comment by Vnrs0** [comment] 2023-06-23 11:05
can confirm this. noticed after I tmogged some lvl 85 items on it and sent it to a twink, the tmog persists through the mailbox as well which wasn't the case on retail cata

**Comment by UltraNix** [comment] 2023-11-22 08:26
Cost will be fixed. But in this case, it's not a bug - it's that expensive.

**Comment by UltraNix** [comment] 2023-11-28 16:42
Fixed.

**Closed by UltraNix** 2023-11-28 16:42 UTC
Labels: Item, Priority: Low
