### ISSUE TITLE
Player error

### ISSUE THREAD

**Issue by Enfasis1** [gamefreedomgit/Maelstrom#4151] opened 2023-08-10 22:34 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Good afternoon, with the entry of the new patch my rogue has lowered its dps considerably, I think the mastery was bugged.  Previously he would burst almost 40k damage and right now he doesn't get to 20k in the burst.  Please, I would like you to review that or if there was any change in the operation of that class, let me know.  My rogue is called Enfasis.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Sketish** [comment] 2023-08-11 07:58
Duplicate of invalid report

**Closed by Sketish** 2023-08-11 07:58 UTC
