### ISSUE TITLE
Dungeon Old Strathholme cant be started

### ISSUE THREAD

**Issue by S1rL00t4l0t** [gamefreedomgit/Maelstrom#4920] opened 2023-10-31 12:52 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The Dungeon Old Strathholme cant be started becasue the scripting of Arthas does not work

**How to reproduce:**
Go to dungeon, speak to Arthas and see what happens

**How it should work:**
Arthas should start an event which will spawn the first mobs

**Database links:**

**Comment by Sketish** [comment] 2023-10-31 13:36
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/2129

**Closed by Sketish** 2023-10-31 13:36 UTC
