### ISSUE TITLE
Shaman Far sight bugg

### ISSUE THREAD

**Issue by MerajMahmoudifar** [gamefreedomgit/Maelstrom#3818] opened 2023-06-13 16:03 UTC
https://github.com/gamefreedomgit/Maelstrom/assets/136472046/6d701a05-015b-49af-aab7-723d166cb7bf

The problem is sometimes I cannot choose farsight location and it automatically selects beneath my foot.
The next problem is in Ghostlands when I farsighted once i got to a channeling an I could attack others no more. I just could cast spells
With regards.

**Comment by UltraNix** [comment] 2023-09-01 08:54
Cannot reproduce it.
@MerajMahmoudifar still happens?

**Comment by UltraNix** [comment] 2023-11-21 14:08
No further info - closing.

**Closed by UltraNix** 2023-11-21 14:08 UTC
Labels: Class: Shaman, Spell, Status: Need Info, Priority: Low
