### ISSUE TITLE
Deathwing Realm: blacksmithing patterns for Vicious Pyrium items yield Bloodied Pyrium items instead

### ISSUE THREAD

**Issue by VinceOrgovan** [gamefreedomgit/Maelstrom#5954] opened 2024-05-10 09:10 UTC
Deathwing PVP Realm
My Death Knight “Overflow” purchased blacksmithing plans for the Vicious Pyrium set from the NPC “Sumi” (Blacksmithing Supplies) in Orgrimmar’s Valley of Honor. These patterns purport to create item level 377 plate armor. However, when crafting the helm and legs patterns, it yields Bloodied Pyrium Helm and Bloodied Pyrium Legguards. These are item level 339 with inferior stats compared to Vicious Pyrium. I suspect the rest of the Vicious Pyrium patterns also yield inferior items, but I have not tried them. Is this a bug in the patterns, or am I doing something wrong? Thank you for making this game available.

**Comment by frostwave942** [comment] 2024-05-10 17:40
it's not a bug. deathwing is in patch 4.0.1 (i think) atm so u cant expect equip items with 377 ilvl

**Comment by PanJanuszek** [comment] 2024-08-20 15:39
closed as not an issue

**Closed by PanJanuszek** 2024-08-20 15:39 UTC
