### ISSUE TITLE
Threat transferring abilties not functioning

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1952] opened 2023-01-17 21:26 UTC
Tricks of the Trade and Misdirection does not trigger when damage is dealt,

video provided by Rqj (rogue) (WARNING, LOUD MUSIC) - https://medal.tv/games/requested/clips/R6HwHKq9g8lka/RfJdy8yf0mP7

**Comment by MullichWhitemane** [comment] 2023-01-29 09:56
The threat transfer now correctly works, however, as long as threat is being transferred, the transferring player's combat flag does not get reset when transferring threat. This means that Rogues can get a free re-stealth every 30 seconds (except if you are Assassin: https://github.com/gamefreedomgit/Maelstrom/issues/1964 - "Venomous Wounds procs (either the energy regen or the damage proc, or both) put both the Rogue and the target in combat.")

**Comment by UltraNix** [comment] 2023-01-30 09:01
I can't reproduce it. Also, check this on non-dummy target.

**Comment by MullichWhitemane** [comment] 2023-01-30 14:21
> I can't reproduce it. Also, check this on non-dummy target.

I've tested on PvE and PvP targets, it seems as if this issue fixed itself? Or there was some other condition I was unaware of whenever I recreated this yesterday. At any rate, it seems to only affect target dummies now, so for now, I'll mark this as a low prio issue.

**Comment by UltraNix** [comment] 2023-01-30 14:37
I would close it as it's caused by special training dummy script (removing combat 5 sec after non-threat action).

**Comment by MullichWhitemane** [comment] 2023-01-30 14:59
> I would close it as it's caused by special training dummy script (removing combat 5 sec after non-threat action).

Very well then, closing for now - will reopen if I manage to recreate the original issue.

**Closed by MullichWhitemane** 2023-01-30 14:59 UTC
Labels: Class: Hunter, Class: Rogue, Spell, Priority: Low, Status: Confirmed
