### ISSUE TITLE
 Event quest : Missing Hierlooms

### ISSUE THREAD

**Issue by MissCllick** [gamefreedomgit/Maelstrom#6222] opened 2024-10-18 13:15 UTC
Quest is not working : u can interact with dead npc.... but after that nothing happends.... quest isnt completed.... question mark is grey

**Comment by Sketish** [comment] 2024-10-18 17:00
Please follow template and provide details what quest and send ss how its looks ingame

**Comment by Sketish** [comment] 2024-10-19 11:06
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6221

**Closed by Sketish** 2024-10-19 11:06 UTC
