### ISSUE TITLE
Unholy pet on other specs

### ISSUE THREAD

**Issue by slim11245** [gamefreedomgit/Maelstrom#2471] opened 2023-03-14 11:56 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Unholy pet with abilities enabled on frost dk and possibly blood spec

**How to reproduce:**
Raise dead enter an instance I used a battleground i no longer had the pet with me, left the instance and returned to where i was with my pet beside me now and I respecced into frost I kept the pet and am able to use abilities.

**How it should work:**
once you respec your pet should no longer gain unholy benefits and abilities

**Database links:**
https://www.wowhead.com/spell=79905/raise-dead

![fpet](https://user-images.githubusercontent.com/127852163/224993641-a2d6a90b-81f0-48e5-9a1a-577752040883.png)

**Comment by UltraNix** [comment] 2023-03-31 19:31
I cannot reproduce this one. After returning from instance/battleground, pet is still despawned.

**Comment by UltraNix** [comment] 2023-04-13 09:40
No further info - closing.

**Comment by UltraNix** [comment] 2023-04-14 17:23
Fixed.

**Closed by UltraNix** 2023-04-14 17:23 UTC
Labels: Class: Death Knight, Status: Need Info, Status: Needs Confirmation, Priority: Medium
