### ISSUE TITLE
[MPG] DS: Zonoz

### ISSUE THREAD

**Issue by vanarenan** [gamefreedomgit/Maelstrom#5309] opened 2023-12-22 22:04 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Ingame name: Horny

**How to reproduce:**
When sphere hiting wall boss becoming non hitable (all misses) while boss isn't moved

**How it should work:**
Should I tell that it shouldn't be like that?

**Comment by Sketish** [comment] 2023-12-22 23:35
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/5288

**Closed by Sketish** 2023-12-22 23:35 UTC
