### ISSUE TITLE
(Heroic) Dungeon - Grim Batol

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Maelstrom#1983] opened 2023-01-21 06:25 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Group Composition (~avg 346ilvl): Bear Tank, Disc Heals, RPaladin, Boomkin, Rogue

Gonna try to go through the list that I wrote chronologically:

-General Umbriss and Forgemaster Throngus worked perfectly.
-The first pack of Trogg Dwellers (in the hallway after killing General Umbriss leading toward Forgemaster Throngus) are supposed to patrol from the hallway to the center part of the forge room. They were standing at the Western entrance to the forge room.
-The Twilight Beguilers are not in their correct spots and don't interact correctly with the Enslaved Gronn Brutes; The TB's should be closer to the Gronn, constantly casting Chained Mind and occasionally the Gronn should knock them back a few yards. After being knocked back, the TB's should run back to their spots and do this over and over.
-The second pack of Trogg Dwellers was either in the floor somewhere or just not spawned in at all.
-The Twilight Wyrmcallers (there should be 2 I believe) either were not spawned in or were somehow killed when we were on the Battered Red Drakes. I'm not sure which, but if we our drakes somehow killed them, they shouldn't be killable by the drakes.
-The mechanics of the fight with Drahga Shadowburner and Valiona worked correctly, but when Valiona reaches 20% health, she should drop Drahga and fly away. When she reached 20% she just disappeared.
-The two Faceless Corruptors patrolling the eggs in the Lifebinder's Cell (before the fight with Erudax) were not there.
-During the fight with Erudax, the start of his [Shadow Gale] cast did not show the shadow of where the players should stand. We had to wait until he began the channeling to see the empty spot in the gale.

Overall, I wanna say that the mobs in here should probably do more damage or have more health (maybe even both). As the tank, I did not come close to dying at all, did not have to use hardly any defensives, and had the lowest ilvl (~339) out of the group.

**Database links:**
Battered Red Drake:
https://cata-twinhead.twinstar.cz/?npc=39294
Trogg Dweller:
https://cata-twinhead.twinstar.cz/?npc=39450
https://cata-twinhead.twinstar.cz/?npc=45467
https://cata-twinhead.twinstar.cz/?npc=48348
Twilight Beguiler:
https://cata-twinhead.twinstar.cz/?npc=48695
https://cata-twinhead.twinstar.cz/?npc=40167
Enslaved Gronn Brute:
https://cata-twinhead.twinstar.cz/?npc=48693
https://cata-twinhead.twinstar.cz/?npc=40166
Twilight Wyrmcaller:
https://cata-twinhead.twinstar.cz/?npc=48754
https://cata-twinhead.twinstar.cz/?npc=39873
Drahga Shadowburner:
https://cata-twinhead.twinstar.cz/?npc=48784
https://cata-twinhead.twinstar.cz/?npc=40319
Valiona:
https://cata-twinhead.twinstar.cz/?npc=40320
https://cata-twinhead.twinstar.cz/?npc=48801
Faceless Corruptor:
https://cata-twinhead.twinstar.cz/?npc=48818
https://cata-twinhead.twinstar.cz/?npc=39392
Erudax <The Duke of Below>:
https://cata-twinhead.twinstar.cz/?npc=48822
https://cata-twinhead.twinstar.cz/?npc=40484
[Shadow Gale]:
https://cata-twinhead.twinstar.cz/?search=shadow+gale#spells

**Comment by WhitemaneSylah** [comment] 2023-02-16 09:57
Duplicate of #1650

**Closed by WhitemaneSylah** 2023-02-16 09:57 UTC
Labels: Dungeon, Status: Duplicate
