### ISSUE TITLE
Quest: The Sacred and the Corrupt #24545

### ISSUE THREAD

**Issue by schney1** [gamefreedomgit/Maelstrom#6328] opened 2024-12-01 15:38 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Arthas does not appear and the Vengeance of Light (mace) cannot be raised.

**How it should work:**
When we enter the cave we freeze, Arthas appears from the bottom and summons ghouls as well as launches the Revenge of the Light (mace) which we have to go to collect so that it kills all the ghouls and allows us to fight with Vegard the Unredeemed and complete the mission. https://www.wowhead.com/wotlk/es/item=49869/venganza-de-la-luz#objective-of

Screenshot: 
![image](https://github.com/user-attachments/assets/b646f21b-38c6-464f-90d7-f89246b2dfe8)

**Database links:**
https://www.wowhead.com/wotlk/es/quest=24545/lo-sagrado-y-lo-corrupto

**Comment by Sketish** [comment] 2024-12-01 19:26
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6134

**Closed by Sketish** 2024-12-01 19:26 UTC
