### ISSUE TITLE
[Achievement] Glutton for Shadowy Punishment - Azshara, Arcane Pinnacle

### ISSUE THREAD

**Issue by chrisdomaub-dev** [gamefreedomgit/Maelstrom#6140] opened 2024-09-08 15:23 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Cannot gain stacks for Glutton for Shadowy Punishment.

**How to reproduce:**
Go to azshara, go to shadowy portal, try to get stacks by making the shadows touch the rune.

**How it should work:**
When a shadow touches a rune and dies, you gain 1 stack. You're supposed to get 20 stacks.

**Database links:**
**Video Link**
https://drive.google.com/file/d/1FmAEl5KVD1xB0ab716PzciM2H3b2Lmtr/view?usp=sharing

**Comment by Sketish** [comment] 2024-09-08 15:48
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6132

**Closed by Sketish** 2024-09-08 15:48 UTC
