### ISSUE TITLE
Deeper into Darkneess Bugged

### ISSUE THREAD

**Issue by hevyd66** [gamefreedomgit/Maelstrom#4506] opened 2023-09-11 11:33 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Skitterweb Matriarch is on the ground and not in line of sight

**How to reproduce:**
Skitterweb Matriarch should be on the ceiling and after getting hit should come down.

**How it should work:**
https://www.youtube.com/watch?v=neOikNxWwk8

**Database links:**
https://www.wowhead.com/quest=27094/deeper-into-darkness

**Comment by Sketish** [comment] 2023-09-12 08:51
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4365

**Closed by Sketish** 2023-09-12 08:51 UTC
