### ISSUE TITLE
[Quest] [Hyjal] Return to the Shrine - slight phasing issue, player required to relog

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#2479] opened 2023-03-14 18:31 UTC
When player has [Return to the Shrine](https://www.wowhead.com/quest=25795/return-to-the-shrine) active and returns Shrine of Aviana for the 1st time, most of the NPCs are missing, including [Choluna](https://www.wowhead.com/npc=41005/choluna). Player has to log out, log in, leave the zone and return to the zone to activate proper phase. So not a big deal in a way but lot of players might not think about it at 1st, I have met some with this problem already.

EDIT: Similar issue seems to be a problem in Firelands Hatchery, where player should relog to seethe NPCs and relog again to get kill credits after he takes the next quest. In general I have seen some phasing issues throughout whole Hyjal, Quest Givers visible on places they should not be yet, or on the other hands staying on the original spot while they should be elsewhere, oftentimes being on both spots at once.

**Comment by UltraNix** [comment] 2023-03-23 17:18
I can't reproduce this one.

**Comment by UltraNix** [comment] 2023-04-11 14:28
No further info - closing.

**Closed by UltraNix** 2023-04-11 14:28 UTC
Labels: Phasing, Status: Needs Confirmation, Zone: Hyjal, Priority: High, Quest
