### ISSUE TITLE
META ACHIEVEMENT 

### ISSUE THREAD

**Issue by YOSHUA2023D** [gamefreedomgit/Maelstrom#4257] opened 2023-08-20 15:19 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
On our guild Inscription was missing for meta achievement, we got all others with honored chars. But this last one didn't complete.

**How to reproduce:**

**How it should work:**

Must give you the meta achievement.
**Database links:**

![WoWScrnShot_082023_111643](https://github.com/gamefreedomgit/Maelstrom/assets/141896582/167f3e26-5837-4d5b-9f4f-bbe4d02230e1)
![WoWScrnShot_082023_111634](https://github.com/gamefreedomgit/Maelstrom/assets/141896582/8a0145f0-2cd8-4629-b749-b10a7649336b)

**Comment by Sketish** [comment] 2023-08-20 19:30
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4075

**Closed by Sketish** 2023-08-20 19:30 UTC
