### ISSUE TITLE
Achievement Stood in the Fire completed without getting killed by Deathwing

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1101] opened 2022-12-12 19:54 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
While in Zul'Farrak, I died by normal mob damage. Upon dieing I received the achievement "Stood in the Fire"

**How to reproduce:**
Die in Zul'Farrak

**How it should work:**
You should only get this achievement when you die by Deathwings fire breath as he flies over you in an open air zone.

**Database links:**

/?achievement=5518

**Comment by UltraNix** [comment] 2022-12-12 21:51
Duplicate of #1059 1087

**Closed by UltraNix** 2022-12-12 21:51 UTC
