### ISSUE TITLE
Spell cooldowns bug 

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#2055] opened 2023-01-30 08:13 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Sometimes when you are in the raid ( did happen in Molten core and in Tempest keep so far) some of your spells are on 4h cooldown after being used ( did happen to empower rune weapon and to goblin racial)
![image](https://user-images.githubusercontent.com/35288643/215421408-3c5f8234-b96e-40ba-af56-39390f99320c.png)

**How to reproduce:**
Go inside any  TBC/Vanilla raid and use some cooldowns it does happen randomly so might take some time

**How it should work:**
It should not put your spells on 4h cooldowns

**Database links:**

**Comment by Greywolf59** [comment] 2023-01-30 22:11
After the 3 (or 4) hours cd was gone, Shouts and trinket too started to work again. Since then I have used .tele and went to many dungeons without a problem. I still clickoff the honorless target buff carefully though.

**Comment by UltraNix** [comment] 2023-02-02 13:12
I can't reproduce it anyway - still persist?

**Comment by sadgh05t** [comment] 2023-02-02 14:32
I will try to run old content raids today and will tell you

**Comment by sadgh05t** [comment] 2023-02-02 15:05
Not happening in the old raids anymore

**Comment by UltraNix** [comment] 2023-02-02 18:20
Closing then.

**Comment by Greywolf59** [comment] 2023-02-02 18:37
Since that 4 hour cooldown happened I had no issue with this no. And I think I seen yesterday someone from the team mentioning somewhere it was fixed.

**Comment by MullichWhitemane** [comment] 2023-02-02 21:09
https://discord.com/channels/1040715551531618365/1070805001963839658

Seems as if this can still trigger, but still not sure why. Won't be re-opening, but rather putting this here for possible good evidence later on.

**Comment by Greywolf59** [comment] 2023-02-08 18:01
Can confirm it is back again. I got caught by server restart/update in Violet Hold. After logging back I have 11h cooldown on Sweeping Strikes. Timezone same as server.

**Comment by MrTide** [comment] 2023-02-09 01:04
update:
 Ceruhia a lvl 29 shaman claimed His HS is on 8h cooldown and happens after every login.. he uses his HS and it has 8h cooldown

**Comment by UltraNix** [comment] 2023-02-10 14:18
@Torpis I can't reproduce it with your tips.

**Comment by MrTide** [comment] 2023-02-11 14:49
looks like it happens with every crash so far.

**Comment by MrTide** [comment] 2023-02-11 20:37
similar issues 
https://github.com/gamefreedomgit/Maelstrom/issues/2141
https://github.com/gamefreedomgit/Maelstrom/issues/2142

**Comment by UltraNix** [comment] 2023-02-14 16:13
Fixed.

**Closed by UltraNix** 2023-02-14 16:13 UTC
Labels: Priority: Critical, Status: Confirmed
