### ISSUE TITLE
Mage impact stun goes through DK anti magic shell

### ISSUE THREAD

**Issue by Hermeleen** [gamefreedomgit/Maelstrom#4986] opened 2023-11-09 10:51 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
I was having shell up and casting hungering cold, mage pressed impant because he couldn't kick me (or so he thought, see #4974 )

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by bonfax4** [comment] 2023-11-09 13:47
It only stops stuff that leaves a magic debuff on you. Impact stun is not magic irrc.

**Comment by Hermeleen** [comment] 2023-11-09 14:47
> ~It only stops stuff that leaves a magic debuff on you. Impact stun is not magic irrc.~ Nvm just read it stops stuff like cyclone so i'm not sure now
> 
> You are right, impact vs shell and no stun [here](https://youtu.be/QU0kE-143eY?t=3)

Thanks Dude, You're the Best. :D

**Comment by UltraNix** [comment] 2023-11-27 18:05
@Hermeleen I cannot reproduce it - impact stun was absorbed. Please, provide some video.

**Comment by UltraNix** [comment] 2024-01-30 12:24
No further info - closing.

**Closed by UltraNix** 2024-01-30 12:24 UTC
Labels: Class: Death Knight, Class: Mage, Spell, Status: Need Info, Priority: Medium
