### ISSUE TITLE
Petattack during camouflage

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#4315] opened 2023-08-25 20:32 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Currently using petattack while in camouflage as a hunter it will break the camouflage

**How to reproduce:**
Play as a hunter, use camouflage and then press petattack and it will break the camouflage

**How it should work:**
Hunter camouflage should not break upon pressing petattack only if the pet hits something.

**Database links:**

**Comment by UltraNix** [comment] 2023-08-25 20:50
What about this one: #4035?

**Comment by Kenniflopper** [comment] 2023-08-25 20:52
Yeah thats basicly the same thing as i reported, didnt see it. Sorry.

**Comment by UltraNix** [comment] 2023-08-25 20:59
And it was resulted with no bug.

**Comment by Kenniflopper** [comment] 2023-08-26 12:39
You should not be removed from camouflage until ur pet hits anything. even if you press petattack.

https://www.youtube.com/watch?v=IDVTNdj22Zk&ab_channel=tgnWorldOfWarcraft 2:25 

@UltraNix

**Comment by bonfax4** [comment] 2023-08-29 07:23
@Afgann How is that proof of anything btw ? The one time he sent his pet to attack at 2:25 he broke camou lol. Not to mention this video is early cata ptr and there's other sources saying it breaks on attack command way past this date.

**Comment by Renehadox** [comment] 2023-09-17 02:30
So this is not a bug?
Why is it marked at a high priority then?
This is invalid bug report.
@UltraNix 
@bonfax4

**Comment by bonfax4** [comment] 2023-09-17 18:55
Was already fixed but they didn't close it yet

**Closed** 2023-09-27 12:56 UTC
Labels: Class: Hunter, Priority: High
