### ISSUE TITLE
Hit chance is bugged

### ISSUE THREAD

**Issue by Feathalise** [gamefreedomgit/Maelstrom#4900] opened 2023-10-28 14:32 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
I should be hit capped but I miss attack

**How to reproduce:**
My hit chance is 8.08%
![image](https://github.com/gamefreedomgit/Maelstrom/assets/11161286/2c9040e1-f11a-466c-a5b9-5ce841c4c149)
but as you can see I still miss attacks
![image](https://github.com/gamefreedomgit/Maelstrom/assets/11161286/d59ed8d3-9315-415a-ade7-5ddd22990b69)
same with pets, when the hunter is hit capped pet should be expertise capped, but pet also misses
![image](https://github.com/gamefreedomgit/Maelstrom/assets/11161286/676657bd-5a43-4a5d-b183-8369ab5c6d4c)

**How it should work:**
I should not miss attacks at 8% hit rate

**Database links:**

**Comment by Renehadox** [comment] 2023-10-28 23:11
The same works for PvP and expertise...

**Comment by UltraNix** [comment] 2023-10-29 06:54
@Feathalise More info please: what class? Against what mob/boss/player class?

**Comment by Feathalise** [comment] 2023-10-29 09:52
Hunter beastmaster, i discovered this while in BD, I later tried it in the dummy boss and continues to happen there so its not specific to one or two bosses

**Comment by oldspices** [comment] 2023-10-29 10:48
shaman thunderstorm is getting lots of misses when i am well over hit cap and never miss any other spells!!

**Comment by Feathalise** [comment] 2023-10-29 10:49
as a side note I dont think its specific to ability either, let me hit the dummy for a while, im sure all abilities will miss

**Comment by Feathalise** [comment] 2023-10-29 11:07
pet melee
![image](https://github.com/gamefreedomgit/Maelstrom/assets/11161286/73539519-b4c8-49f6-9143-acca6bfdc174)

pet bite
![image](https://github.com/gamefreedomgit/Maelstrom/assets/11161286/8defd25f-683e-4f31-91ad-c2b5f2de8828)


auto shot
![image](https://github.com/gamefreedomgit/Maelstrom/assets/11161286/80e4968a-7b84-4e0a-9b34-8cd4d7d7c638)

**Comment by Feathalise** [comment] 2023-10-29 11:09
also pet having 25% of melee being glancing blows greatly reduces damage

**Comment by Feathalise** [comment] 2023-10-29 11:13
So as of right now hit capped is bugged, next time im at a raid ill make sure to take a look at missed abilities, but this should be plenty already, probably hit formula is bugged because if other classes report the same issue then I assume its that, a bug somewhere is making hit cap slightly bigger then it is.

Im not going to reforge all my gear but I assume if I raised my hit cap by a bit I probably wont miss, but thats a bug

**Comment by Pornoodemon** [comment] 2023-10-30 21:01
With 5% Hit chance, my Felguard pet sometimes misses when I use stun. So this problem is most likely of a general nature.

**Comment by Feathalise** [comment] 2023-10-31 10:07
you can see from my pic what boss it is, its the scientist guy, also you shouldnt get blocks either way, attacking from the back is no solution as its not realistic scenario for raiding, other people also report hit chance issues, so there is something there but not for meto figure out as I no longer play here, good luck with that

**Comment by bonfax4** [comment] 2023-10-31 10:28
You're wrong about that,  [certain bosses can block](https://www.mmo-champion.com/threads/1243903-Raid-bosses-blocking-attacks) and positioning shouldn't be an issue anyway since the should be facing away generally.

**Comment by bonfax4** [comment] 2023-10-31 10:33
either way i guess @Ultranix  can go test hit against maloriak or maloriak adds to see what's the issue. I can't replicate this on anything else currently.

**Comment by UltraNix** [comment] 2023-10-31 10:37
Also tested and also can't reproduce it with my hunter spells/auto shot, nor with pet abilities.
So yeah - @Feathalise we would need more info or you can poke me on Discord to see if it still happens.

**Comment by bonfax4** [comment] 2023-10-31 10:49
> With 5% Hit chance, my Felguard pet sometimes misses when I use stun. So this problem is most likely of a general nature.

There's still certain scenarios where you can miss while "hit capped" btw with phys abiltiies at least. Ex : against Nelf players. You guys should take SS's of these scenarios and post to account for every variable.

**Comment by bonfax4** [comment] 2023-10-31 11:11
Yh nvm, testing 5% hit vs lvl 85 dummies on warlock and i see misses and dodges. 

![bf2bfd205cbc665453ba469c3ed8502c](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/7da163f1-6a92-4237-8778-4bc0852b0ce0)

**Comment by bonfax4** [comment] 2023-10-31 11:33
Yh i think whatever formula is being used should account for target level and level caps but it always assumes your max spell hit , so you still need 17% against lvl 85's.

**Comment by Pornoodemon** [comment] 2023-10-31 15:26
> > With 5% Hit chance, my Felguard pet sometimes misses when I use stun. So this problem is most likely of a general nature.
> 
> There's still certain scenarios where you can miss while "hit capped" btw with phys abiltiies at least. Ex : against Nelf players. You guys should take SS's of these scenarios and post to account for every variable.

With a 5% chance of hitting, I missed in pvp with different classes mage, dk, warrior at the start of the duel

**Comment by UltraNix** [comment] 2023-10-31 16:25
But wait - since when 5% is hit cap?

**Comment by bonfax4** [comment] 2023-10-31 16:27
Against lvl 85. He's talking about pvp

**Comment by UltraNix** [comment] 2023-10-31 17:32
`Tested and felguard is missing/dodging with 5% against lvl 85 as shown above. I even tested with 10% and still missed.`
How you modified that? Simply adding items with spell hit? Or maybe some aura/talent with spell hit?

**Comment by UltraNix** [comment] 2023-10-31 18:02
Hmm. But 5% spell hit is not 5% melee hit chance.
So you are only 5% spell hit (17 is cap as I recall), so your pet is proportionally melee hit chance.
5/17 = 0,3
0,3*8 = 2,4.

**Comment by Pornoodemon** [comment] 2023-10-31 18:23
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/67071992-9038-4a8f-a6cb-1eeee985f794)
In melee combat there is a 1% miss chance.
Но bonfax4 проверял на 10 % и тоже промахнулся .

**Comment by UltraNix** [comment] 2023-10-31 18:35
10/17 = 0,59
0,59 * 8  = 4,7
So still a chance to get miss.

**Comment by UltraNix** [comment] 2023-10-31 18:47
Warlock pets take your spell hit and converts it to melee hit. It's not 1:1 ratio (the same goes for expertise)

**Comment by bonfax4** [comment] 2023-10-31 19:27
I tested 5, 10 and then 17% and that's when I didn't miss.  My point is why is 17% being assumed in a formula against a lvl 85 ? 17 would be against a lvl 88 or boss lvl.

Don't you think if 17% ( following your formula you posted, 17 is the hit cap )  was the pvp spellhit cap that pvp guides wouldn't mention it ?  Or that there would be at least a mention of it in discussions ? 

17 is not even reachable with full pvp gear if we're being honest, unless you equip some pve hit trinkets and reforge away from every stat.

**Comment by bonfax4** [comment] 2023-10-31 19:28
Missing spell lock/seduction would be critical in 3v3

**Comment by Pornoodemon** [comment] 2023-10-31 19:32
> Warlock pets take your spell hit and converts it to melee hit. It's not 1:1 ratio (the same goes for expertise)

Well, the fact of the matter is that, as far as I know, 100% of the warlock’s accuracy should be transferred to the pet.
For example, the same as resilience
And even in all pvp guides the accuracy cap is indicated at 4%.

**Comment by bonfax4** [comment] 2023-10-31 19:42
Btw simc does show that spell hit converts 1:1 to melee hit for locks but I dunno if this was actually tested or made purely for the sake of simplicity. No idea how blizzard actually calculates this stuff but I'll hop on retail wotlk ptr tomorrow and test.

**Comment by UltraNix** [comment] 2023-10-31 19:55
@Pornoodemon Any links to these guides?

**Comment by Pornoodemon** [comment] 2023-10-31 20:03
> @PornoodemonЕсть ссылки на эти руководства?
https://www.youtube.com/watch?v=NGElZ1oBSCI

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133828891/17cc8d8e-4c72-466a-9edb-11aac662ce60)

**Comment by UltraNix** [comment] 2023-10-31 20:04
C'mon - I don't know Russian :P

**Comment by bonfax4** [comment] 2023-10-31 20:07
Pretty sure it's 5% in cata, 4% is wotlk

**Comment by Pornoodemon** [comment] 2023-10-31 20:10
> C'mon - I don't know Russian :P

https://youtu.be/NGElZ1oBSCI?si=L5-k6jNVJ2_Xdh_a&t=26

**Comment by UltraNix** [comment] 2023-11-08 17:12
Fixed.

**Closed by UltraNix** 2023-11-08 17:12 UTC
Labels: Core, Priority: High
