### ISSUE TITLE
Holy Priest Spell Guardian Spirit doesn't work correctly.

### ISSUE THREAD

**Issue by Silliaq** [gamefreedomgit/Maelstrom#4560] opened 2023-09-19 10:11 UTC
Description:
4 days ago I noticed an incorrect operation of the spell Guardian Spirit. After talking with another holy priest I realized that this problem affects all holy priests.
I wrote to support, but didn't receive an answer.
When I use this spell on myself it doesn't give me 50% health back instead it turns me into a Spirit of Redemption. However when I use it on other players it works correctly.
By the way in the statistics on the battegrounds death points are not counted.
During a duel using this spell it doesn't work death occurs turns me into a Spirit f Redemption but the duel does not end.
The priest I spoke with wrote a ticket but the problem was not resolved.

How to reproduce:

How it should work: 
should restore 50% health back to myself.

Database links: 
[https://paste.pics/f1d0f4830e773e590648edb5105abb54]
[(https://paste.pics/c556cce373539de395d1306538defef2)]
[https://paste.pics/0f822f2a9b2ff8c1bb2285cf67d21f10]

**Comment by Sketish** [comment] 2023-09-19 14:38
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4531

**Closed by Sketish** 2023-09-19 14:38 UTC
