### ISSUE TITLE
[Death Knight ZONE][Quest][An End to All Things... completed]

### ISSUE THREAD

**Issue by Orcmage** [gamefreedomgit/Maelstrom#1509] opened 2022-12-31 13:32 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
-You need to be in very close proximity when killing them to get credit

**How to reproduce:**
Kill Crusaders or Ballista from a distance

**How it should work:**
You should always get credit when you kill them

**Database links:**
/?quest=12779

**Comment by WhitemaneSylah** [comment] 2022-12-31 13:33
Closed as dupe of #1508

**Closed by WhitemaneSylah** 2022-12-31 13:33 UTC
Labels: Class: Death Knight, Status: Duplicate
