### ISSUE TITLE
Darkmoon Card Hurricane

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#3866] opened 2023-06-20 14:47 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
The item does not do the correct amount of damage.

**How to reproduce:**
Test it on training dummy and player.

**How it should work:**
It should do 7000 to the training dummy not 3500

**Database links:**
https://cata-twinhead.twinstar.cz/?item=62051

**Comment by MadeinNoxus** [comment] 2023-06-21 03:24
Same as https://github.com/gamefreedomgit/Maelstrom/issues/3295

**Comment by Sketish** [comment] 2023-06-21 07:24
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/3295

**Closed by Sketish** 2023-06-21 07:24 UTC
