### ISSUE TITLE
Deep into darkness mission

### ISSUE THREAD

**Issue by Rottenass** [gamefreedomgit/Maelstrom#4594] opened 2023-09-22 20:50 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is a mission '' deep into darkness '' where you have to kill a boss spider in a cave.But you can't because the boss is bugged and you can't attack it no matter what you do.I tried chaning region , i tried abandoning and re taking the mission , i tried any kinda weapon , i tried everything it is just bugged.

**How to reproduce:**

**How it should work:**
I saw on youtube that the spider is supposed to be on the roof but in this private server is not.The spider is on the ground with spiderweb from the roof to the spider's ass.So i belive it is just broken or something , the animation is not correct and you can't interact with it.

**Database links:**

**Comment by Sketish** [comment] 2023-09-23 08:08
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4365

**Closed by Sketish** 2023-09-23 08:08 UTC
