### ISSUE TITLE
[Core] Equipping Weapon Resets GCD

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1177] opened 2022-12-13 23:36 UTC
fytchx
OP
 — 12/10/2022 1:54 PM
when you equip a weapon, it resets your global cooldown

**Comment by UltraNix** [comment] 2022-12-14 19:03
@Loken-coolguy I can't reproduce it. In combat, you are allowed to change weapon once per 1.5 sec.

**Comment by MrTide** [comment] 2022-12-22 15:37
I can't reproduce it neither gonna close it

**Closed by MrTide** 2022-12-22 15:37 UTC
Labels: Core, Status: Need Info, Priority: High, Status: Needs Confirmation, Bug Report from Discord
