### ISSUE TITLE
Wild Growth bug just at Ultraxion

### ISSUE THREAD

**Issue by mushexz** [gamefreedomgit/Maelstrom#5400] opened 2023-12-31 13:46 UTC
https://wowpedia.fandom.com/wiki/Wild_Growth

**Description:**
Hi, wild growth is a spell that I use very often. It can be pressed having a friendly/enemy as a target, or without any target at all.

**How to reproduce:**
Ultraxion has a spell that I must to keep an eye on, so I keep my target on the boss to see the casting bar. When he's closer to finish the casting spell, we must press a button that sends us to another realm. However I've noticed that pretty often, IF i keep the target on him, and press the Wild Growth spell, its just wasting my mana without providing any heal at all, not even on myself, even though there's players in my realm. But the moment I take the target off him, it works :) 

**How it should work:**
Based on the link I've sent, the spell should hit 6 people if I keep the target on a friendly, or 5 if I keep the target on an enemy. At other bosses I couldn't notice this bug. Just at Ultraxion where, for me at least, its necessary to see his casting bar.

**Comment by Waroxx-QA** [comment] 2023-12-31 18:39
Using mouseover macro ?

**Comment by bonfax4** [comment] 2023-12-31 18:52
6 target thing is not a cata thing btw. You can confirm in videos that it doesn't hit more than 5 when a friendly target is selected.

https://youtu.be/kXM_f7lj1FY?t=5s

**Comment by mushexz** [comment] 2023-12-31 23:51
I use Healbot, its much faster than clicking target and then pressing a key.  I did not test it myself how many targets its healing, but in that case it ain't healing anything at all

**Comment by Waroxx-QA** [comment] 2024-01-01 18:32
> 6 target thing is not a cata thing btw. You can confirm in videos that it doesn't hit more than 5 when a friendly target is selected, outside of tree form ofc.
> 
> https://youtu.be/kXM_f7lj1FY?t=5s druid in the video is not even using mouseover macros, he's click target and healing lol

@bonfax4 Wild growth affects 5 players, 6 if you have the Glyph of Wild Growth.

But it's not the subject of the report.

**Comment by bonfax4** [comment] 2024-01-01 18:42
> > 6 target thing is not a cata thing btw. You can confirm in videos that it doesn't hit more than 5 when a friendly target is selected, outside of tree form ofc.
> > https://youtu.be/kXM_f7lj1FY?t=5s druid in the video is not even using mouseover macros, he's click target and healing lol
> 
> @bonfax4 Wild growth affects 5 players, 6 if you have the Glyph of Wild Growth.
> 
> But it's not the subject of the report.


Nah, he also added it should hit 6 targets if you target a friendly target which is a functionality from another xpac. Either way we won't be able to tell if it's blizzlike anyway because nobody really targeted ultraxion to wild growth honestly, and I bet the issue is with the huge boss hitbox and not the spell itself.

**Comment by Waroxx-QA** [comment] 2024-01-01 18:52
Mouseover macro ( or Healbot ) is targeting, so it should hit 6 targets. if you use it without Mouseover / Healbot and targeting the boss it should hit 5 players so it's about the boss hitbox.

**Comment by bonfax4** [comment] 2024-01-01 19:02
I know but it would still hit 5 ( or 6 ) depending on glyphs regardless of the target tho, if 5-6 eligible people were within range of the enemy target ofc. It's either target + 4 (unglyphed ) if friendly or 5-6 people around enemy target.

**Comment by Waroxx-QA** [comment] 2024-01-01 22:29
> I know but it would still hit 5 ( or 6 ) depending on glyphs regardless of the target tho, if 5-6 eligible people were within range of the enemy target ofc. It's either target + 4 (unglyphed, 5 flyphed ) if friendly or 5-6 people around enemy target.

if you're targeting an enemy, it counts as you are targeting yourself, so you get hit + 4 or 5 other party members ( depends on glyph ) as far as i know.

**Comment by bonfax4** [comment] 2024-01-01 22:47
It targets around the enemy. You can even find mentions of it working that way in wotlk. I can dig up for you if you'd like. No idea of it's prioritizing enemy target over mouseover tho, which would be an issue.

**Comment by bonfax4** [comment] 2024-01-01 23:14
And I was wrong about one thing, even if you target a friendly target, it should still pick 5 people around you that are low. It's possible it doesn't actually pick your target. Saw it happen on the video above and it goes matches how they describe it works back in wotlk.

https://dreambound-druid.blogspot.com/2009/03/wild-growth.html?m=1

It always targets the 5-6 with the lower health % people around your target/mouseover, not always your target.

https://youtu.be/kXM_f7lj1FY?t=2m You can see it happen here, he casts a wild growth with no target which is self cast, and it lands on 5 different people, not including himself.

**Comment by UltraNix** [comment] 2024-01-02 16:02
`Heals up to $s3 friendly party or raid members within $A1 yards of the target `
**of the target**
if you select enemy, then it calculates on your enemy.

**Comment by Waroxx-QA** [comment] 2024-01-02 17:41
![Screenshot_2024-01-02-18-40-48-62_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/gamefreedomgit/Maelstrom/assets/120338315/59210a3d-596f-40d9-b7d9-810a31340ed9)

**Comment by bonfax4** [comment] 2024-01-02 17:45
It doesn't work that way...  This is a cata video of somebody that doesn't know the mechanics https://youtu.be/Sk-8NRmNMUc?t=1s... Wild growth is not even going through because of los

**Comment by UltraNix** [comment] 2024-01-02 17:48
I'm thinking about big bosses, like Ultraxion, Ragnaros or Alakir. What should happen there if you are targeting enemy?

**Comment by bonfax4** [comment] 2024-01-02 17:56
You see some random comments saying edge of hitbox but I dunno how trustworthy that is..

https://www.wowhead.com/forums/topic/wild-growth-how-when-where-165809

**Comment by UltraNix** [comment] 2024-01-03 09:23
Basically it's the same.

**Comment by Waroxx-QA** [comment] 2024-01-03 11:18
[Rdudu targeting the boss - Healing 6 targets](https://youtu.be/myXq10T-kgg?si=RBJL2snJuwjAr9y1)

**Comment by bonfax4** [comment] 2024-01-03 13:34
Yeah that video isn't conclusive enough, he's hiding his cursor and using mouseover macros. 

Unless the bug is that the target is being prioritized over mouseover which is possible too.

**Comment by bonfax4** [comment] 2024-01-03 13:41
Best way to test this honestly is classic wotlk ptr honestly, the behaviour is exactly the same from that xpac, nothing major was changed or documented to change between the 2 expansions

**Comment by UltraNix** [comment] 2024-01-09 16:10
Due to lack of info - closing it.
I will re-open it once some evidences shows up.

**Closed by UltraNix** 2024-01-09 16:10 UTC
Labels: Class: Druid, Status: Need Info, Raid: Dragon Soul
