### ISSUE TITLE
[Quest] Three Little Pygmies

### ISSUE THREAD

**Issue by DeadRatsYT** [gamefreedomgit/Maelstrom#2288] opened 2023-03-02 07:17 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
If you hit the mob while using rocket boots he stuck flying. and it makes him almost impossible to kill. he jumps on your head and become in Evade state. Also happen to zombies when you trying to hit them without boots.

Seems like geo data is weird. If you come into zone where the pygmies spawn they go down to ur level. and sometimes fall under the ground. but you can kill them at least.

Also you pick up this quests from village on the server instead of next to Oostan entrance. 

![image](https://user-images.githubusercontent.com/99285606/222357520-ec17ca9d-f7df-4d4b-9d68-8500a1a668d4.png)
![image](https://user-images.githubusercontent.com/99285606/222357878-bf901616-6ce0-4f55-9e0f-a57cb72c7a36.png)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment] 2023-03-24 12:19
I can't reproduce any of these bugs.

**Comment by UltraNix** [comment] 2023-04-18 12:09
No further info - closing.

**Closed by UltraNix** 2023-04-18 12:09 UTC
Labels: Status: Needs Confirmation, Priority: Critical, Quest
