### ISSUE TITLE
[Rogue] Smoke bomb AEO dmg/healing 

### ISSUE THREAD

**Issue by Dimzy2** [gamefreedomgit/Maelstrom#4303] opened 2023-08-24 20:46 UTC
[//]: # (https://cata-twinhead.twinstar.cz/?spell=103558)

**Description:**
Anything inside Smoke bomb don't work like it used to be 
1- Rsham link don't Work inside Smoke bomb even when allies are inside the bomb 
2-Aoe don't work inside bomb 
**How to reproduce:**

**How it should work:**
Link should share health with allies inside the bomb and out side shouldn't 
Rogues are abusing it in arena with double Smoke bomb 

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=103558

**Comment by Sketish** [comment] 2023-08-25 10:37
We need  retail videos to proof things you are reporting

**Comment by Qidpuncher-outland** [comment] 2023-08-26 11:34
Im pretty sure bombing a link shouldnt work but idk about other aoe's so lets say you hymn inside it if it should heal the targets outside since its basically just reversed of what works.

**Comment by bonfax4** [comment] 2023-09-02 17:38
@sketish watch the priest and druid los'd using Tranquility/ Divine Hymn when the rogue was about to get trained inside a smoke bomb to keep him up , check gladius frames 
 @2:03. https://youtu.be/fUpmCp7L4Fc?si=3cWu3khOjyhGxGdy.

Dmg aoe / grounded aoe should also go through I've seen it in videos before but cba to find them. Spirit link not sure, but earthbind goes through it so logically I'd assume so.

**Comment by mipanka** [comment] 2023-09-04 00:10
not a bug, spirit link should not work in bomb

**Comment by bonfax4** [comment] 2023-09-05 11:17
Confirmed in couple videos spirit link does not go through smoke bomb, regardless if everyone is inside or not so that's working as intended.

Slow dow these videos to 0.25 :

https://youtu.be/gqIAQ2xZzCc?t=1m2s
Shaman pops link outside bomb while warlock is inside and no hp redistribution, spirit link gets killed after so link was nullified completely.

https://youtu.be/Yh1GXrLJQzI?t=37s
Shaman links with all 3 group members inside bomb and no redistribution, 2 other members remained at 100% hp.

**Comment by UltraNix** [comment] 2023-09-28 16:25
So there is a bug here? @bonfax4

**Comment by bonfax4** [comment] 2023-09-28 16:37
Yes, currently aoe heals are not going through smokebomb ( didn't test aoe dmg but guy above said it's also not working ) when they should. Spirit link interaction is fine.

**Comment by UltraNix** [comment] 2023-09-29 11:34
@bonfax4 Can you give me some examples of such AoE heals? I tested shaman and druid -  all okay.

**Comment by bonfax4** [comment] 2023-09-29 11:51
@UltraNix 
Was a while ago but I remember a partner complaining divine hymn didn't work through it.

**Comment by UltraNix** [comment] 2023-09-29 12:30
![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/5681c4da-b7cf-4621-a088-fb06f642c85e)

**Comment by UltraNix** [comment] 2023-09-29 12:48
No - own smoke bomb.
If you are in enemy's smoke bomb, then you should not be able to heal that person.

**Comment by bonfax4** [comment] 2023-09-29 12:51
No check the video above. Untargeted apes go through enemy smoke bomb

**Comment by bonfax4** [comment] 2023-09-29 13:06
If you need confirmation that smokebomb on the video was done by the attacking rogue, the hunter was attacking the enemy rogue into the smokebomb from outside and also unfriendly smokebombs have a red aura to them.

**Comment by UltraNix** [comment] 2023-09-29 13:10
@bonfax4 So it does not matter if it's enemy's or mine smoke bomb? You can always target and heal targets inside smoke bomb (even being outside it)? And it would be weird, if only applicable to AoE.

**Comment by bonfax4** [comment] 2023-09-29 13:14
Your own smokebomb should not affect anything at all on your own teammmates. Your healer should even be able to use direct heals on you.

 Enemy smokebombs just stops targeted spells. Untargeted Aoe heals should still go through.

**Comment by bonfax4** [comment] 2023-09-29 13:20
Ok so everything is fine then, you can close this.

**Closed** 2023-09-29 13:21 UTC
Labels: Class: Rogue, Priority: Medium
