### ISSUE TITLE
Achievment stood in fire bugged

### ISSUE THREAD

**Issue by Drakegamer456879** [gamefreedomgit/Maelstrom#6144] opened 2024-09-09 22:04 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Even tho i died to deathwing a couple times before, the achievement says its not completed yet

**How to reproduce:**

**How it should work:**
Normally when u die to deathwing in open world or in ds, u should get the achiev

**Database links:**

**Comment by Sketish** [comment] 2024-09-10 07:41
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6141

**Closed by Sketish** 2024-09-10 07:41 UTC
