### ISSUE TITLE
Priest Atonement healing bug

### ISSUE THREAD

**Issue by RobertKDroid** [gamefreedomgit/Maelstrom#3339] opened 2023-05-04 18:15 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # ([Atonement](https://cata-twinhead.twinstar.cz/?spell=81749))

**Description:**
Atonement does not heals on some bosses, sometimes it prioritizes pets over players also

**How to reproduce:**
Atonement does not works at all at al akir in TOT4w

**How it should work:**
Well it should heal + proritize players

**Database links:**

**Comment by Sketish** [comment] 2023-05-04 20:36
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/2212

**Closed by Sketish** 2023-05-04 20:36 UTC
