### ISSUE TITLE
DireMaul North: Gordok Tribute loot table bugged

### ISSUE THREAD

**Issue by Priestelar** [gamefreedomgit/Maelstrom#4435] opened 2023-09-04 13:00 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When spawning the tribute, the loot table is bugged, it will often drop no blue gear and only consumables.

**How to reproduce:**
Kill only the king and not Cho'Rush then talk to the npc that spawns and complete the dialogue options.

**How it should work:**
When the king is dead, Cho'Rush changes friendly. An NPC from the south starts running to the king's arena, you and youre entire party must now talk to him and you receive the "King of the Ogres" buff. You are now friendly to the entire instance. After everyone talks to the NPC, the tribute chest will appear with some mana/hp pots, some BoP greens and 3 RARES. It also has a chance to drop Treant's Bane(I saw that drop 5 runs ago). In total, 5 Rares will drop on this Tribute Run.

**Database links:**
https://www.wowhead.com/classic/object=179564/gordok-tribute#contains;mode:normal

**Comment by Sketish** [comment] 2023-09-04 14:45
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4397

**Closed by Sketish** 2023-09-04 14:45 UTC

**Comment by Priestelar** [comment] 2023-09-08 10:31
@Sketish This issue is different than #4397 as that thread is a boss spawn issue, this thread is about a loot issue on a treasure chest. 

Despite what the other thread mentions, it IS possible to get the chest to spawn, you dont need all the bosses to spawn for it to work
