### ISSUE TITLE
darkmoon volcano rarely procs

### ISSUE THREAD

**Issue by Fystorm** [gamefreedomgit/Maelstrom#3106] opened 2023-04-18 10:54 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Alandiel** [comment] 2023-04-18 10:59
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/2915

**Closed by Alandiel** 2023-04-18 10:59 UTC
