### ISSUE TITLE
Templar Veredict missing a aura modifier of 30%

### ISSUE THREAD

**Issue by RamiroBaraza** [gamefreedomgit/Maelstrom#5169] opened 2023-12-08 17:53 UTC
Description: 
Templar Veredict is unafected by Crusade talent from Retribution talent tree, wich should give an extra 30% damage to some spells.

How to reproduce:
Clear your talent tree, select Retribution spec and check TV tooltip and scaling. Original scaling with 0 modifiers is 235% weapon damage for 3 holy power usage. You can check that original scaling of 235% on the OG patch notes: https://wowpedia.fandom.com/wiki/Patch_4.0.1_(class_changes)#Retribution

Then select the 3 points on the talent "Crusade" (retribution tree, first row, mid talent) and save talent changes. Check TV tooltip and you can see that the tooltip is now updated with extra scaling, but the damage still the same. You can check the internal scaling doesn't change with addons like DrDamage, or you can perform some damage tests and check the average.

How it should work:
Cusade talent should be giving the 30% extra damage to TV as described

Database links:
https://cata-twinhead.twinstar.cz/?spell=85256
https://cata-twinhead.twinstar.cz/?spell=31868

**Comment by bonfax4** [comment] 2023-12-08 22:41
@Afgann make sure you double check this. Last time I tested it was working. #4881

**Comment by bonfax4** [comment] 2023-12-08 22:58
I do see some recent changes to spellmods so those test conditions are not the same.

```Author: afgann
Message: Core/Player: Fix calculating multiple SPELLMOD_PCT spellmods. ```

**Comment by Renehadox** [comment] 2023-12-09 00:43
Everything is undertuned under powered about rets on this server...

**Comment by RamiroBaraza** [comment] 2023-12-09 01:44
I forgot to add some in-game screenshots that shows both the tooltip and the average calculated damage from DrDamage

No Glyph and no Crusade 30% talent:
https://i.imgur.com/AmsAKnU.png

Glyph added for 15% extra damage, you can see both the tooltip and the average expected damage raised:
https://i.imgur.com/XAANCPi.png

Now with Crusade talent, tooltip updates but not the DrDamage average expected damage, also damage seems to don't raise up:
https://i.imgur.com/9XmYfcg.png

**Comment by bonfax4** [comment] 2023-12-09 01:52
Link logs instead of tooltips. Use the same weapon I used on the tests I did with no dmg variance on the PTR realm

**Comment by Renehadox** [comment] 2023-12-09 01:55
> Link logs instead of tooltips. Use the same [weapon](https://cata-twinhead.twinstar.cz/?item=57692) I used on the tests I did with no dmg variance on the PTR realm

Why are you poking your nose on every ret paladin bug that shows lower damage than intended?

What's your goal?

**Comment by bonfax4** [comment] 2023-12-09 02:11
@Renehadox Not even gonna bother with you, you're allergic to proper testing.

**Comment by Renehadox** [comment] 2023-12-10 01:24
Confirmed, the talent doesn't increase TV damage.

This is a huge issue...

**Comment by bonfax4** [comment] 2023-12-11 19:10
If the ptr is not behind on the changes crusade is working....

**Comment by Renehadox** [comment] 2023-12-11 20:47
> @Renehadox Not even gonna bother with you, you're allergic to proper testing.

I just did your test " mr allergic to proper testing "

Crusade talent only works for crusader strike it doesn't work on TV like the guy above stated with actual proofs ( Screenshots of Dr. Damage addon ).

**Comment by bonfax4** [comment] 2023-12-11 21:04
I tested with TV.... Dr damage does now work how you think it works. The only thing bugged he confirmed is the tooltip which ultimately doesn't matter if the dmg is correct.

**Comment by Crusaderz** [comment] 2023-12-12 13:57
Tested on the live server on a level 3 dummy.

The description displays correctly. 
235% without glyph and talent
270% with glyph (2.35 * 1.15)
351% with 3/3 Crusade (2.7 * 1.3)

Talent works correctly, glyph works correctly. Almost.

The damage on the doll is 3% less than the calculated damage, weapon min damage (2034-2042) * 3.51

You can write it off to armor, but this percentage varies depending on damage modifications.

No talents, no glyph = 0.05% less.
Got talent = 0.4% less
Got talent and glyph = 3% less.

It's weird.

**Comment by bonfax4** [comment] 2023-12-12 15:42
Talent and glyph are additive btw so it's a 1.45x mod when both are up.

**Comment by Renehadox** [comment] 2023-12-12 15:57
> I tested with TV.... Dr damage does now work how you think it works. The only thing bugged he confirmed is the tooltip which ultimately doesn't matter if the dmg is correct.

he said that the damage is lower.

On a side note, is it me or whenever a ret paladin bug is reported there is a huge shitload of debate going on with " needing videos from retail " 

where on others classes they are marked as critical/high without proofs from retail? :D

**Comment by Crusaderz** [comment] 2023-12-12 16:05
@bonfax4 

> Your final multiplier should be about @3.4 and not 3.51.

351% in [this](https://youtu.be/UQIALBpf4gA?t=837) 12 years old video:
![image](https://github.com/gamefreedomgit/Maelstrom/assets/3641625/ff8ed8c2-aedd-45ff-b3b7-7ee6e7522d5c)

> Also I'm assuming you have other multipliers in play like the 3% aura ? I never fully talented when I tested.

Nope. Talent+Glyph so I don't understand why it turns out to be 3% less damage.

**Comment by bonfax4** [comment] 2023-12-12 16:09
It rounds to 351% jf your fully talented as 2.35*1.45*1.03 which is @3.51 (3.509725)

**Comment by bonfax4** [comment] 2023-12-12 16:19
Hmm the simc files say otherwise

![image](https://github.com/gamefreedomgit/Maelstrom/assets/16911730/c2cfa949-d00d-49a8-a496-4208dc8866c8)

**Comment by bonfax4** [comment] 2023-12-12 16:27
Also tooltips are not always correct when it comes to spellmods, so it will never be a guaranteed on how the spell should behave. I remember going through shaman elitistjerks and they had issues with them not being accurate. Same for hunter pets I believe

**Comment by Crusaderz** [comment] 2023-12-12 17:02
@bonfax4 

1. The paladin in the video doesn't have any auras enabled and only gets +2% damage from the Communion talent.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/3641625/d6e75ec7-2e1b-424b-b0ec-e1d503aa7e0b)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/3641625/5e2f9f6f-adc1-4e51-baa5-ec4a3f193266)


2. The 2% damage bonus should not affect the % of weapon damage of Templar's Verdict, and if it does, it's double dipping because it already gives a bonus to melee damage.

3. But let's pretend that double dipping does happen and it affects the weapon's damage percentage

2.35 x 1.45 x **1.02** = 3.47565, that's not 351%.

**Comment by bonfax4** [comment] 2023-12-12 17:21
Just run the sim and see honestly. I don't put too much faith in Tooltips. I now noticed that Dr damage is also additive when you look at the multipliers. Both the theorycraft tools say additive, while tooltip says multiplicative and I would put more faith on the tools. Dr dmg is applying multipliers to the AP to normalized weapon dmg conversion.

3.3 / 14 * 1.45 =  0.34178... ( 0.342 ) as shown on the SS op linked ( the multiplier just went straight to 1.45 when one of the choices was picked, why it didn't change ).

**Comment by Renehadox** [comment] 2023-12-12 21:09
Keep up the debate regarding rets.


Buff Ferals, MM hunters and sub rogues more.

Continue it... please 23 comments, only 23???

Go make it 53

**Comment by bonfax4** [comment] 2023-12-14 14:16
Yeah they def changed smthing now that I properly retested. Its not additive anymore like the tests i did earlier on that other post. Seems to be multiplicative now in some way

**Comment by bonfax4** [comment] 2023-12-14 14:19
> Message: Core/Player: Fix calculating multiple SPELLMOD_PCT spellmods. ```

I do wonder now if every class will have higher numbers tho if this was the change that changed the dmg output.

**Comment by Renehadox** [comment] 2023-12-16 17:41
So with this bug whats gonna happen its not marked?

**Comment by Renehadox** [comment] 2023-12-26 22:50
> I forgot to add some in-game screenshots that shows both the tooltip and the average calculated damage from DrDamage
> 
> No Glyph and no Crusade 30% talent: https://i.imgur.com/AmsAKnU.png
> 
> Glyph added for 15% extra damage, you can see both the tooltip and the average expected damage raised: https://i.imgur.com/XAANCPi.png
> 
> Now with Crusade talent, tooltip updates but not the DrDamage average expected damage, also damage seems to don't raise up: https://i.imgur.com/9XmYfcg.png

@Afgann @Sketish @UltraNix 

can you guys check this?

**Comment by Waroxx-QA** [comment] 2023-12-28 08:16
i tried without crusader it does 32 dmg, with 1* crusader (10%) does around 35, with 30% it does 42 so it's working.

**Comment by UltraNix** [comment] 2024-01-17 17:36
Tooltip for this spells is really fucked up by blizzard - don;t look at it.
Also - spellmods on our server are additive, not multiplicative.

**Comment by Renehadox** [comment] 2024-01-18 01:44
> Tooltip for this spells is really fucked up by blizzard - don;t look at it. Also - spellmods on our server are additive, not multiplicative.

so the talent works properly or what is it?

Is templars working properly or not i dont get your comment?

**Comment by Sketish** [comment] 2024-01-18 07:33
> i tried without crusader it does 32 dmg, with 1* crusader (10%) does around 35, with 30% it does 42 so it's working.

Read comments. Talent is working

**Closed** 2024-01-31 20:45 UTC
Labels: Class: Paladin, Priority: High
