### ISSUE TITLE
[Quest] Call of Duty  dont work 

### ISSUE THREAD

**Issue by Fromtill** [gamefreedomgit/Maelstrom#1130] opened 2022-12-13 19:18 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
According to #1061 or #1030, now we can receive the follow up quest.
but as you can see in the screenshot below, the quest is automatically failed and you can re-accept it in a infinity loop.
![image](https://user-images.githubusercontent.com/120294125/207424970-506e1fce-a3f7-4a9c-a7d4-3cec4d41b532.png)
Curently the ship to the new area do not move!

**How to reproduce:**

accept the follow up quest "call of duty"

**How it should work:**

After accepting the quest "Call of Duty", you should go to the docks, where the ship waits.
After a scripted scenario, you can ship to the starting area.
Please find a full sample of the quest here:
https://www.youtube.com/watch?v=NZLRijak0Pg

**Database links:**
![image](https://user-images.githubusercontent.com/120294125/207424863-21b96ba0-506f-4d79-bcf3-ca0f682bfbb1.png)

**Comment by UltraNix** [comment] 2022-12-13 20:23
The fix was about adding the follow-up quest. This report is about something different.

**Comment by Fromtill** [comment] 2022-12-13 21:07
> The fix was about adding the follow-up quest. This report is about something different.

Yes your right!

**Comment by UltraNix** [comment] 2022-12-22 09:13
Quest is not disabled due to unscripted event.

**Comment by MrTide** [comment] 2023-01-07 19:37
Confirmed event is not working at all
requires attention, its a bottle neck

**Comment by Torpis** [comment] 2023-01-10 06:45
Confirming it still isn't working - ideally need to get this one working for launch, but could really do with it resolving before then so we can test Vash'jir quests.

A lot of the script looks good, all the RP plays out - it just needs the boat to arrive and then take the player to Vash'jir.

**Comment by WhitemaneSylah** [comment] 2023-01-11 00:50
Alliance side #1797

**Closed** 2023-11-14 09:30 UTC
Labels: Status: Confirmed, Status: Needs Confirmation
