### ISSUE TITLE
Issue with Rhyolith

### ISSUE THREAD

**Issue by devvotion** [gamefreedomgit/Maelstrom#4337] opened 2023-08-27 21:02 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
He will not turn properly... no dots on a leg, no pets, 0 damage on it and he just goes forward

**How to reproduce:**
Just have a group doing it.... it was seriously frustrating, we all drop damage from the left leg, start going on the right one, no dots on left, yet he still just keeps going forward

**How it should work:**
He should turn...

**Database links:**

**Comment by Sketish** [comment] 2023-08-28 11:20
Duplicate of https://youtu.be/pUpicZaUDTA?t=17

**Closed by Sketish** 2023-08-28 11:20 UTC
