### ISSUE TITLE
[Rogue Ability] Redirect ability does not redirect combo points

### ISSUE THREAD

**Issue by initialactivity** [gamefreedomgit/Maelstrom#3633] opened 2023-05-27 12:00 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Redirect ability should redirect combo points to a new target when this ability is used

**How to reproduce:**
Get combo points on one target. Switch targets. Use Redirect.

**How it should work:**
It should move the combo points to the new target
**_This should work even when you move combo points from a dead target._**

**Database links:**
http://cata-shoot.tauri.hu/?spell=73981

**Comment by Sketish** [comment] 2023-05-28 08:09
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/3614

**Closed by Sketish** 2023-05-28 08:09 UTC
