### ISSUE TITLE
Brew of the Month spam

### ISSUE THREAD

**Issue by Zeehra** [gamefreedomgit/Maelstrom#4753] opened 2023-10-12 14:33 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After getting Brew of the Month for 4 or 5 characters, they are now all receiving mail from the brew dude twice a day at least, often more. The mails, which are supposed to come once a month with a sample of the month's brew, are all empty save for the text.

**How to reproduce:**
Complete the Brew of the Month quest and watch your mailbox get flooded with dumb shit.

**How it should work:**
There should only be one mail per month and it should contain a sample of the brew of the month. Please make the spamming stop :')

**Database links:**
https://imgur.com/a/TgJmFQi
https://www.wowhead.com/achievement=2796/brew-of-the-month

**Comment by UltraNix** [comment] 2023-10-12 17:51
Duplicate of #4687

**Closed by UltraNix** 2023-10-12 17:51 UTC
Labels: Priority: Medium, GameEvent

**Comment by Zeehra** [comment] 2023-10-13 00:18
Not exactly a duplicate, but an additional issue, that I commented on on #4687. But since no action was taken, I opened a proper ticket specifically for this to ad as much detail as possible.

**Comment by Zeehra** [comment] 2023-10-20 08:54
And also, don't close it as "completed", I still get 10 new mails every single day. Sheesh. Literally nothing changed.
