### ISSUE TITLE
hp pet

### ISSUE THREAD

**Issue by pro100klass** [gamefreedomgit/Maelstrom#4247] opened 2023-08-19 09:21 UTC
Why is the pet's HP decreasing?
https://www.youtube.com/watch?v=QWE4U9RAYT4

**Comment by Sketish** [comment] 2023-08-19 10:08
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4176

**Closed by Sketish** 2023-08-19 10:08 UTC
