### ISSUE TITLE
Master of the Molten Flow - Shaman portion not working correctly

### ISSUE THREAD

**Issue by Elfy279** [gamefreedomgit/Maelstrom#6154] opened 2024-09-15 10:36 UTC
I've tried killing shaman with the fire aoe, and the lava missile, without damaging the shaman myself

I've tried dpsing the shaman down and letting either get final hit, and nothing awards me completion

**Comment by Sketish** [comment] 2024-09-15 12:53
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6149

**Closed by Sketish** 2024-09-15 12:53 UTC
