### ISSUE TITLE
Eating Freezing Trap Not Possible

### ISSUE THREAD

**Issue by lishpeth** [gamefreedomgit/Maelstrom#4647] opened 2023-09-30 08:21 UTC
**Description:**

Currently, on the server, there is something wrong with eating Freezing Trap. If a player Scatter Shoted or Blinded by a hunter and stands still while the trap is casted, it is nearly impossible for another player to stop and eat that trap. 

https://wowwiki-archive.fandom.com/wiki/Freezing_Trap

As in the link above, the freezing trap should have 1 second arming time exactly. 

https://www.twitch.tv/nybergx/clip/RelatedExuberantSnakeAMPEnergyCherry-AjqByrOTMsKD1ILG

This video above belongs to the Maelstorm server and it is nearly impossible to eat the trap as shown in the video. The trap seems like, it chooses the first standing still person whatever you do. Freezing trap acts like it doesn't have an arming time or a chance to trap someone else sitting on the trap to eat it. 

**How to reproduce:** 

Cast Scatter Shot and Freezing Trap when you have two or more NPCs on top of each other. The one who was there first even before the arming time of the freezing trap will be trapped. 

**How it should work:** 

https://www.youtube.com/watch?v=aU8pOwuqt3k&ab_channel=ComplexityGaming

This video belongs to Retail Cataclysm and as you can see, the healer is scattered, another person sitting on the trap and has a chance to be able to eat the trap. At 3:36, the trap lands, and two players are on top of the trap. The trap has 1 second arming time. The healer is scattered, so wandering around and other player still standing eats the trap.

I myself have also a hunter on this server and whenever I want to trap someone even if they are on top of each other to stop my trap, I can trap the target with Scatter Shot or Bad Manner with ease. Because it seems like the person who was standing still even before the trap lands and is armed has a very high chance of being trapped. 

**Database links:** https://wowwiki-archive.fandom.com/wiki/Freezing_Trap

**Comment by SimonBpvp** [comment] 2023-09-30 18:54
-1 I think hunter trap is working fine on whitemane, the clip from nybergx shows a trap scripting hunter and he needs reported to a GM.

**Comment by whothatdog** [comment] 2023-09-30 20:24
Must to say: I am not a pvp player nor doing or done it much.

on **some** retail-videos it seems people have chance to get trapped instead of the real 'targeted' by move to 'eat' the trap instead the targeted one with higher chance.
to my eyes it look like the 'game' is punishing hunters and favor players who stand/position themselves against those bad hunters.

while on **some** other retail-videos it seems that even if you stand 0.001y to eat the trap it still doesn't make you take it instead of the real target.

It's hard to decide what to do in this cases when it's not clearcut.

I am pretty sure it is annoying for some people who forces to use their abilities like Sprint, Heroic Leap, Teleport, Blink, and other gap-closers, Grounding and more to eat trap and it does not work.

I am not sure how it should work by 'code-wise' all I can do is to share my opinion:

I assume the trap has like very low radius. (we see it on the green thingy when hunter use trap launcher)

If it was up to me as programmer I probably would make it **least** to prefer people who are under cc (bad manner, scatter shot, polymorph, throwdown, hoj etc)
and prefer un-cc'd targets.

the meaning of it will be: if hunter cc target, somebody run/manage to reach that small/low radius of trap **on time**
the trap will prefer the un-cc'd one.

else:
if cc-targeted get trap and nobody (un-cc'd players) tried or success to come inside that low-radius the real cc'd target will eat the trap.

but 'we' try to mimic as much as possible blizzlike, we cannot be sure it's blizzlike intentions.
or atleast my intentions are similar to blizzlike designers.

it might be 'nerf' for hunters many won't like playing and changing it's behavior/AI much.

**Comment by SimonBpvp** [comment] 2023-10-01 02:23
Yeah mate I didn’t just look at the title and close the tab, I actually watched the clip and saw him flying in disengage while launching a perfect trap so please…

anyway you’re wrong about how trap should work, it shouldn’t prioritise anything other than which char gets his centre closest to the centre of the trap so all that nonsense about if somebody heroic leaps or blinks to it is irrelevant. Now if people keep trap scripting maybe they should look at doing a custom change to trap launcher but that’s a suggestion for another time.

**Comment by whothatdog** [comment] 2023-10-01 03:56
> Yeah mate I didn’t just look at the title and close the tab, I actually watched the clip and saw him flying in disengage while launching a perfect trap so please…
> 
> anyway you’re wrong about how trap should work, it shouldn’t prioritise anything other than which char gets his centre closest to the centre of the trap so all that nonsense about if somebody heroic leaps or blinks to it is irrelevant. Now if people keep trap scripting maybe they should look at doing a custom change to trap launcher but that’s a suggestion for another time.

I wasn't wrong about how trap work because I did not wrote how it work at all
If by somehow it understood that way from my previous message - I am sorry.
I just gave my own opinion about how I think they should make it work.
That's all.

me either, I watched that clip, nice disengage and perfect trap for camera movement it require
it still ain't mean it was a trap script.

I mean, this person keba which claimed to be a scripter and recorded on that clip
is not here to defend himself, you know..

in my opinion: what nyberg which I remember from Apollo probably complain about
is he perfectly stood on it while bladestorming and it still ain't prefered him over the cc'd target.
>"it **chooses** the first **standing** still person whatever you do"

must mention - on kenni's pov streams I saw enemy-warlock eating traps instead shaman few times.

something to note:
the example nyberg gave => how should it work vs how it should not work:
on the youtube vid the Hunter used Scatter Shot which causes the target to wandering around
while on the twitch-clip it was Bad Manner which does not make player to wandering around but stand still.

better if the comparsion was bad manner-whitemane vs bad manner-blizz
or 
scatter vs scatter

just compare apples to apples.

p.s
Simon, no doubt your pvp exp is greater than mine.

**Comment by lishpeth** [comment] 2023-10-01 07:49
If you want a comparison with scatter + trap vs. scatter + trap, here it is.

This one belongs to Tosan - a master of trapping - he scatters the player - that player is wandering around as it should and his teammate standing on the trap = eats the trap. Check the video at 6:16.

https://www.youtube.com/watch?v=J9kNEWD6egg&t=17s&ab_channel=TosanTribe

And here again; on Maelstrom. A player got scatter shotted - not wandering around widely as in the original Cataclysm and instantly got trapped. I wanted to show you the wandering distance here. Scattershot acts like you are blinded and you stand still. In actual Cataclysm, it made you move forward and backward like in Tosan's video but not on this server. So I think this is one of the reasons why scatter + trap always lands a trap on the desired player whatever you do. It is at 25:29 on the video:

https://www.twitch.tv/videos/1934115345 

And here; there are 3 players standing on top of the trap to eat it and again the target with Bad Manner gets trapped. 33:33 on the video:

https://www.twitch.tv/videos/1934115345

Come on. There should be a %33 chance that you can eat the trap if 3 people standing on it. 

I have never seen such easiness of trapping in my life. I leveled a hunter here on this server and hit 85. My last time playing in PVP as a hunter was back in the days of retail Cataclysm. Even my traps landed perfectly every time here. Think about it. How easy here to trap even if you are new to Hunter.

It is instant and undodgeable. Developers should at least check it.

I can find lots of proof like this if you want more.

**Comment by lishpeth** [comment] 2023-10-01 08:00
And if you have video or proof for Maelstorm showing Bad Manner + trap not working every time, please share.

**Comment by whothatdog** [comment] 2023-10-01 12:06
You see the discussion is good, it make devs to understand it better what the issue is about.

for Scatter Shot:
I tested scatter shot and compared the wandering around movement on Whitemane
I am too lazy to record it with video and upload, so you will have to believe my arrow I draw.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/3508d3fb-49a2-429d-8986-f334f79150bb)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/d464911e-e092-4045-9336-9b8425af37fc)

I made more tests the results are more or less the same, not wide wandering, at one time no wandering at all only
character stood on place and just faced different directions but stood in place.

for Bad Manner:
about the 33:33 bad manner & trap.
let's assume there 33% chance for each player since they stand very close / together.
if that's is our assumption: it still possbile on **this** specific-try - it just worked on the paladin who had the bad manner cc.

to check this to the highest accuracy it require like 30/60/90 tries of trapping when 3 people stand on same location
while the 'main target' would cc by bad manner and trap land on same coordinate point (x,y) 
then we can see if the probability is 33% for all or not.

I am out of capabilities to make those kind of experiments.

**Comment by UltraNix** [comment] 2023-10-02 19:12
There is a 1 sec arming trap on Freezing.
And traps always get the nearest target to it.
https://www.twitch.tv/nybergx/clip/RelatedExuberantSnakeAMPEnergyCherry-AjqByrOTMsKD1ILG - on that video both staying at the same spot - random pickup.

[https://www.twitch.tv/videos/1934115345 - 25:29](https://www.twitch.tv/videos/1934115345) - you can clearly see that paladin is the nearest to trap

[https://www.twitch.tv/videos/1934115345 - 33:33](https://www.twitch.tv/videos/1934115345) - same as above - hunter casted trap under the pala

**Comment by whothatdog** [comment] 2023-10-02 23:27
@UltraNix 
the issue opener is kinda right about the Scatter Shot is not wandering around wider.

clip(whitemane):
https://streamable.com/a24bzw (2 days to watch)

about the trap:
Perhaps by any chance it should not work **only** with who is the closest to the middle(centre) of the trap 
but in there additional conditional 'statement(s)'?

(like I suggested to check targets cc / un-cc status and it prefer un-cc targets, but who knows.)

Like look [this](https://www.youtube.com/watch?v=uxYgZMaR9zU):
Warlock - Scatter Shot
DK - Sap.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/0c495c75-9c91-4cc7-9f38-e542e4f166bf)

who get the trap?
the dk. although to my human eyes it look like the warlock is closer to the trap.
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/d887e1b9-a14b-4db8-9bcb-44c8e95520c9)

a disclaimer:
in that exact same video he trapped a Warlock when to my human eyes the warlock pet was very near the trap aswell
it prefered the warlock over the pet.

another example [here](https://www.youtube.com/watch?v=J9kNEWD6egg) at 5:48
scatter on priest, trap (not by launcher, but if slow motion the video you will see it on ground)
the mage got it (you can see it on frames) & to my human eyes the priest is closer to it.

Disclaimer: on the same exact video at 6:40 a priest scatter into trap when feral is near by him but far than the trap for sure.
Disclaimer2: "" "" "" "" at 11:24 he trapped shaman when it seems that warlock is pretty closer.

I did some tries with trap on Whitemane it's **extremely precise**.

More tries on Freezing Trap:
Warlock vs Warlock pet
total score: 8-1
[trap location](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/6ed3931f-1698-40dd-9187-ea55a26570a0)) : [who trapped](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/b7a67c7e-3c1b-4475-962d-61b2c4b143c2))
[trap location](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/90acdd23-917a-4f53-83ca-6b0dd5248188)) : [who trapped](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/877b3b21-d9cf-4256-b430-4f6ec1559c19))
[trap location](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/5bb3b1ce-828b-485b-a120-53a565d61904)) : [who trapped](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/7f75e96d-1346-46db-8669-e0444d76dd8b))
[trap location](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/30af5e13-e50e-4728-941a-36f67aadb931)) : who [trapped](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/a37de293-52a8-4b75-8a94-6a3d32ea404c))
[trap location](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/c44058d6-6539-4b51-9f26-97891b2deb34)) : [who trapped](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/00424c48-2b95-472c-be4f-d200c8e3ae19))

I inceased the distance between warlock and pet
on those two tries I throw the trap closer to the pet:
warlock vs pet
total score: 0-2
[trap location](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/4484d174-d7ff-4add-b5b7-bd4cb7e8205a)) : [who trapped](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/3dade82a-c63f-428b-91d5-bee8e47bd82b))
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/56ceb90e-556d-4aeb-980c-0044576ecd5a) : [who trapped](![image](https://github.com/gamefreedomgit/Maelstrom/assets/143028214/f53cf559-ac6b-4569-948d-850e7f9cfa9f))

I did two tries with favor warlock it was 2-0 to warlock vs pet.

so my conclusions are - trap is seems very accurate ~ if the condition is centre / no bugs or something there
scatter shot wandering need to be bit wider.

**Comment by UltraNix** [comment] 2023-10-03 16:51
@whothatdog If you think that wandering distance of scatter shot is not correct, then you should open a new report as this one does not cover it.
About trap activation distance: yep - it's very precise and should be.

**Comment by whothatdog** [comment] 2023-10-03 18:37
Oh, hmm... I don't want 'shitting' this issue.
but the issue-opener spoke about Scatter Shot on his first message and I did few comments here to help out that's all.
> "If a player **Scatter Shoted** or Blinded by a hunter and stands still while the trap is casted"

Also, It's not the **distance** of using the ability, It's about the way the player/target under the effect moving around.
I added clip showing it opener in my opinion is correct there very little movement.

btw, I don't mind to open an new issue about it, but isn't this issue just about that?
like I am sorry if I understand it different than others.

About trap activation:
you wrote -
> "both staying at the same spot - random pickup."

I tested it out and the result (although small number of tries) was for me 8-1 between warlock and warlock's pet.
I added screenshots, it doesn't look like there any random pickup.

I just suggested to add to the random pickup a new conditional state to check cc / un-cc status and prefer
the un-cc. (not really blizzlike)
like if player2 stand 0.501 yard and player2 stand 0.502 yard it will prefer the un-cc one.
for fairness gameplay.
because if a un-cc player decided to try to eat the trap and 'wasted' some cd for it
it deserve to choose him. in the clip of the opener he bladestormed and instead of moving toward the hunter
and damage him, he bladestorm 'nothing' and went to the location of his priest healer.

btw, I wonder if there is like a limitation from below? like how close to the 'centre' it will just random pickup
0.5 < X, 0.5 > X, closer?

Anyway, I will stop to comment here.

**Comment by lishpeth** [comment] 2023-10-03 19:37
Yeah, I can open a new issue about scatter shot not acting Blizzlike on this server. 

The thing is here, even after the scatter shot is fixed as it should act, Blind + Trap is still undodgeable cc on the server. Trap seems to favor the person in Bad Manner almost all the time. I didn't come across with proof the other way around. 

And to cap it all, Hunters are messing around dismissing pets the whole day in the arena. The only way to stop the hunter is to cc the hunter when he uses Bad Manner. Standing still on the trap to eat doesn't feel like it favors your trying time. 

Like in the video, I have linked; three people were standing on the trap with the blinded person, and the person in Bad Manner cc was trapped.

So, it would be totally worth it if the developers could check the function of the freezing trap.

**Comment by Mongo69** [comment] 2023-10-26 17:58
Yeah -1 for this one,this sounds like skill issue or some1 who hasnt played cata at all

Traps work correctly.

Had no issues eating traps what so ever,and you are linking videos from 2011 back when people had no idea how to aim trap under persons feet as hunter lol 
(if hunters aims trap under feet you wont ever eat it,that's how it works)

This report is a simple skill issue,should be closed.

**Comment by UltraNix** [comment] 2024-04-16 14:41
No further info - closing.

**Closed by UltraNix** 2024-04-16 14:41 UTC
Labels: Class: Hunter, Status: Need Info, PVP: Mechanic
