### ISSUE TITLE
Quest: Therazane's Mercy

### ISSUE THREAD

**Issue by ParaCani** [gamefreedomgit/Maelstrom#6248] opened 2024-10-22 18:49 UTC
Character with issue: Skarsnik (not tested on other Chars)
Quest: Therazane's Mercy

Description:
Simple Killquest, defeat two named NPC's 
1. Boldrich Stonerender (no issue)
2. High Priestess Lorthuna (issue)

Defeating High Priestess Lorthuna does not count towards completing the quest.
Fighting, pathing, animation, dialogue, etc. are working just fine

How to reproduce:
Defeat High Priestess Lorthuna, she runs away before you can kill her, as intended. But the quest does not get completed.
Abandon quest and repeating the process does not work.

How it should work:
Defeat High Priestess Lorthuna, she runs away with some dialogue, quest gets completed.

[https://www.wowhead.com/quest=26832/therazanes-mercy](url)

**Comment by Sketish** [comment] 2024-10-23 07:13
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6246

**Closed by Sketish** 2024-10-23 07:13 UTC
