### ISSUE TITLE
[Quest][Object] Mostly Harmless

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#2351] opened 2023-03-06 03:57 UTC
The Quest Mostly Harmless
https://www.wowhead.com/quest=27536/mostly-harmless
seems to be bugged with either the mines not respawning or the player is not getting phased to them.

**Comment by DorizarN** [comment] 2023-05-13 11:44
I can confirm that there looks to be some sort of phasing bug.

Quest: https://cata-twinhead.twinstar.cz/?quest=27536#issues
Where to fins the mines: https://cata-twinhead.twinstar.cz/?object=205545

I've flown around for a few minutes, could only find 1 mine.

**Comment by Aurorre** [comment] 2023-09-29 09:54
I tried what 3 other topics said with re log/ reload/ retake quest and leave zone come back. They still haven't spawned.

Description: The mission cannot be done because the mines that must be disarmed according to the mission are missing.

How to reproduce: Only accept the quest

How it should work: There should be mines on the ground that unlocking them will give you the following quest item: https://www.wowhead.com/item=61349/disarmed-land-mine

Database links: https://www.wowhead.com/quest=27536/mostly-harmless
https://cata-twinhead.twinstar.cz/?quest=27536

**Comment by PanJanuszek** [comment] 2024-04-15 11:09
should be fixed as for 15.04.2024

**Closed by PanJanuszek** 2024-04-15 11:09 UTC
Labels: Gameobject, Quest
