### ISSUE TITLE
Quest "To New Thalanaar"

### ISSUE THREAD

**Issue by Toeclipper** [gamefreedomgit/Maelstrom#3199] opened 2023-04-25 11:42 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**  Flight takes you to Ruins of Feathermoon instead of New Thalanaar.

**How to reproduce:** Take the Quest

**How it should work:** Should take you from Shadebough to New Thalanaar

**Database links:**

**Comment by Sketish** [comment] 2023-04-26 07:59
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/2932

**Closed by Sketish** 2023-04-26 07:59 UTC
