### ISSUE TITLE
[Worgen][Racial] Two Forms

### ISSUE THREAD

**Issue by HectorHendrix** [gamefreedomgit/Maelstrom#2515] opened 2023-03-16 05:51 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Vuelves a tu otra forma

**How to reproduce:**

El cambio de forma de humano a huargen se activa automáticamente al atacar y no cuando el jugador quiera

**How it should work:**

El cambio de forma se debe activar cuando el jugador quiera a excepción si activa ímpetu oscuro o impulso salvaje

**Database links:**

https://www.wowhead.com/es/spell=68996/dos-formas

**Comment by Loken-coolguy** [comment] 2023-03-22 23:39
Description:
You return to your other form

How to reproduce:

The shapeshift from human to worgen triggers automatically when attacking and not when the player wants to

How it should work:

The shapeshift must be activated whenever the player wants except if they activate dark rush or wild rush

Database links:

https://www.wowhead.com/en/spell=68996/two-ways

**Comment by UltraNix** [comment] 2023-04-12 17:24
Cannot reproduce it.
@HectorHendrix Still happens?

**Comment by UltraNix** [comment] 2023-05-30 07:09
No further info - closing.

**Closed by UltraNix** 2023-05-30 07:09 UTC
Labels: Spell, Core, Status: Need Info, Status: Needs Confirmation
