### ISSUE TITLE
[Quest and NPC] Blood to Thrive and Mazoga

### ISSUE THREAD

**Issue by MadeinNoxus** [gamefreedomgit/Maelstrom#2259] opened 2023-02-28 08:43 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Mazoga doesn't give the quest Blood to the Thrive

**How to reproduce:**
Try to talk with Mazoga in Tanaris

**How it should work:**
https://www.youtube.com/watch?v=n_jU8Y6KJPY&ab_channel=WorldOfWarcraftGuidesAndGameplay

**Database links:**
https://www.wowhead.com/quest=25021/blood-to-thrive

**Comment by Greywolf59** [comment] 2023-02-28 17:04
Duplicate of: https://github.com/gamefreedomgit/Maelstrom/issues/1939

**Closed** 2023-02-28 19:18 UTC
