### ISSUE TITLE
2 minute afk timer in rateds

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4535] opened 2023-09-15 23:16 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
we don't need this feature in rateds imo, cause sometimes people defending a base will get kicked even though they are doing their job watching the node.

**How to reproduce:**
if you wait 2 mins and don't do anything it will kick u from the game and u cant return

**How it should work:**
not needed in rateds imo

**Database links:**

**Comment by Sketish** [comment] 2023-09-16 12:28
So its suggestion not a bug report, closing

**Closed by Sketish** 2023-09-16 12:28 UTC
