### ISSUE TITLE
Achievement "Hallowed Be Thy Name" completion issue

### ISSUE THREAD

**Issue by Aodriver** [gamefreedomgit/Maelstrom#4837] opened 2023-10-21 20:36 UTC
[//]: # https://www.wowhead.com/wotlk/achievement=1656/hallowed-be-thy-name#

**Description:**
Achievement "Hallowed Be Thy Name" not completing. Achievement "Sinister Calling" not tracking correct in criteria for completion.

**How to reproduce:**
Add all achievements required for "Hallowed Be Thy Name". Possibly add "Feline Familiar" on another character then add the helm to the character with all the achievements on to complete "Sinister Calling" - (that's how i completed it, it might still bug even if you just add the achievement to yourself anyway)

**How it should work:**
Once all the criteria has been met for the achievement in question, achievement should complete.

**Database links:**
![Screenshot 2023-10-21 211912](https://github.com/gamefreedomgit/Maelstrom/assets/148656036/dd17ef63-b0f7-4595-a4fd-225ec425283a)

![Screenshot 2023-10-21 212005](https://github.com/gamefreedomgit/Maelstrom/assets/148656036/0f76de82-84f9-4651-a1ad-83e055f0babb)

**Comment by frostwave942** [comment] 2023-10-21 21:30
i notice the same thing: it seems that wide acc achivs were "partially" implemented and may be the points are not adding up for alts.

**Comment by Aodriver** [comment] 2023-10-21 21:40
All of my achievements were completed by the same character in this case.

**Comment by frostwave942** [comment] 2023-10-21 23:09
i'm having issues with <a href="https://www.wowhead.com/achievement=1041/rotten-hallow">rotten hallow</a> (horde) i'm missing the quest <a href="https://www.wowhead.com/quest=29376/a-time-to-build-up">a time to build up</a> idk if this quest rotates with <a href="https://www.wowhead.com/quest=29377/a-time-to-break-down">a time to break down</a> every 06:00 st or if its definetly bug.

**Comment by UltraNix** [comment] 2023-10-25 19:51
@Aodriver Cannot reproduce it. 
"Feline Familiar" does not completes achievement "Sinister Calling"
Tell me: you had Hallowed Helm part already completed when got Sinister Calling achiev?

**Comment by UltraNix** [comment] 2024-01-30 11:20
No further info - closing.

**Closed by UltraNix** 2024-01-30 11:20 UTC
Labels: Status: Need Info, Achievement, GameEvent
