### ISSUE TITLE
[Aura Issue] Magma

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2731] opened 2023-03-30 13:56 UTC
**How to reproduce:**
Aura Magma stuck on Players pet and can't be removed by game masters due removal of the command usage on npcs from GM toolkit
![image](https://user-images.githubusercontent.com/36106057/228858923-1b174e98-13ad-4e38-9792-594637984bf2.png)
This issue happens in OS: https://wowpedia.fandom.com/wiki/Obsidian_Sanctum
Player with the issue 
![image](https://user-images.githubusercontent.com/36106057/228859522-d1f2b74a-a85c-4e46-a10a-67a055938c32.png)

**How it should work:**
it should not stay on players nor their pets
Spell: https://cata-twinhead.twinstar.cz/?spell=57634

**Comment by UltraNix** [comment] 2024-02-28 18:20
@MrTide Still a thing? I can't reproduce it after testing with hunter and DK pets.

**Comment by UltraNix** [comment] 2024-04-16 15:07
No further info - closing.

**Closed by UltraNix** 2024-04-16 15:07 UTC
Labels: Spell, Status: Need Info, Status: Confirmed, Raid: Vanilla/TBC/WotLK
