### ISSUE TITLE
Death knight talent points issues

### ISSUE THREAD

**Issue by sadgh05t** [gamefreedomgit/Maelstrom#1888] opened 2023-01-14 19:30 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
When you doing the quests that give you +1/2 talents sometimes it bugs out and you can not spend them ( and not able to spend the talents received after encountering the bug ). Reload, relog, and clear cache are not working. The available workaround is to buy a dual-spec switch and switch back to the main spec. On the start you need those talents to level up faster, so please add a BOP  item to every starting DK which you can sell to NPC for 10 g so you can have the dual spec at the start and not be worried about the talents bug

**How to reproduce:**
Create a new DK do a few quests that give you talent points 

**How it should work:**
You should be able to receive and spend your talent points without any issues

**Database links:**

**Comment by MullichWhitemane** [comment] 2023-01-22 09:37
Couldn't recreate this issue on a recently made Death Knight, talent points are all given out as intended, If possible, please try to recreate the exact scenario that produced this issue for you.

**Comment by sadgh05t** [comment] 2023-01-22 16:41
Sure will test it today

**Comment by sadgh05t** [comment] 2023-01-22 18:32
I believe there was a fix it does work fine right now

**Comment by MullichWhitemane** [comment] 2023-01-22 18:52
Closing this then as solved.

**Closed by MullichWhitemane** 2023-01-22 18:52 UTC
Labels: Class: Death Knight, Status: Need Info
