### ISSUE TITLE
[Serious][Talent] Can't learn talents after level 33

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#1469] opened 2022-12-28 16:16 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
There is a strange bug where I can't learn talents after level 33. I click to learn it, it says "Are you sure you want to learn", after clicking confirm the Talent Tree goes back to normal.

Could be linked to https://github.com/gamefreedomgit/Maelstrom/issues/1470

**How to reproduce:**
Level to 31 inserting every talent along the way, then ding 33 and try to insert the next talent point. In my case, it did not let me.

I've tried the following troubleshooting:

Reload UI
Disable all Addons
Relog

**The following resolved the issue:

Visting trainer, paying 10g to Learn Dual Spec, switching specs, then switching back, then spend the talent point**

![Confirming Talent Selection](https://user-images.githubusercontent.com/6482585/209840814-35c08a8b-135c-451c-b04a-b8e28a786541.PNG)
![Talent Tree Reverts to Previous](https://user-images.githubusercontent.com/6482585/209840816-9f153b22-df0e-43f3-b7ba-2b429e67cf76.PNG)

**How it should work:**
Should be able to learn talents without needing to mess around with dual spec.

**Database links:**

**Comment by MrTide** [comment] 2022-12-30 13:40
works fine for me, did you try deleting the cache folder and relaunching the game ?
i can't reproduce this

**Comment by Torpis** [comment] 2022-12-30 15:50
Yeah I didn't think this would be reproducable to be honest. I didn't delete cache, I logged out and back in, then went and learnt Dual-Spec.

Could a potential fix be to give everyone dual-spec at level 30 that way if they get bugged then they can easily switch or is that not something that the team wants to do? Just concerned when you have 1000s of players this could happen a couple of hundred times if it happened to me.

**Comment by Orcmage** [comment] 2022-12-31 21:06
This happened to me on my Paladin at level 39 today.
Earlier I did not get awarded my talent point at level 37. When I dinged 39 I did however get a talent point, but it is impossible to learn it. When I assign it to a talent, it gets reset upon clicking "Learn".
At level 33 I had no such problem.
related info in https://github.com/gamefreedomgit/Maelstrom/issues/1470

**Comment by Orcmage** [comment] 2022-12-31 21:33
Update:
At level 41 I got another talent point. I was able to assign and learn this new talent point, but the one received at level 39 remains "floating" and unable to be assigned.
The one I should have gotten at 37 is still missing.

**Comment by UltraNix** [comment] 2023-02-02 18:18
I belive it should be already fixed.

**Closed by UltraNix** 2023-02-02 18:18 UTC
Labels: Class: Paladin, Talent, Priority: Medium, Priority: Critical, Status: Confirmed
