### ISSUE TITLE
BUG MISION " THE LINK "

### ISSUE THREAD

**Issue by duquedekull** [gamefreedomgit/Maelstrom#6255] opened 2024-10-25 10:48 UTC
Hello, the mission "The Link" has a bug. When I kill the priestess, it counts the mission as completed and I get the yellow question mark, but I don't see any NPC to deliver the mission.

**Comment by GMNeon** [comment] 2024-10-25 11:00
26971 - [The Binding]  - https://www.wowhead.com/cata/quest=26971/the-binding
Phase error due to deepholm. Is 4 should be 524288

**Comment by Sketish** [comment] 2024-10-25 15:00
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/6252 and https://github.com/gamefreedomgit/Maelstrom/issues/6256

**Closed by Sketish** 2024-10-25 15:00 UTC
