### ISSUE TITLE
[Item] Titanium Seal of Dalaran

### ISSUE THREAD

**Issue by cataboomie** [gamefreedomgit/Maelstrom#3790] opened 2023-06-09 18:33 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)
https://imgur.com/a/3HsnQbg

**Description:**
When I use 'Titanium Seal of Dalaran' literally nothing happens. My character should throw a coin up and pick it again and there should be an message in chat like on the photo.

**How to reproduce:**

**How it should work:**
There should be an message in chat:
"name" casually flips his 'Titanium Seal of Dalaran'
"name" catches the coin ... 

**Database links:**

**Comment by Alandiel** [comment] 2023-06-10 18:42
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/3353

**Closed by Alandiel** 2023-06-10 18:42 UTC
