### ISSUE TITLE
Cross-Faction BG issues 

### ISSUE THREAD

**Issue by MullichWhitemane** [gamefreedomgit/Maelstrom#2382] opened 2023-03-07 19:14 UTC
Currently, at the very least for Horde players being moved to Alliance side on BGs, it is impossible to interact with certain objectives. From this report, I can only confirm Drek'thar and various objectives such as flags in AV or AB. This issue is possibly global.
![C fact bg](https://user-images.githubusercontent.com/121984461/223526806-dc1e11f8-e12a-404f-b80a-26a8641ae584.PNG)

**Comment by UltraNix** [comment] 2023-03-07 20:13
AB/AV flags will be fixed, but I can't reproduce problems with bosses/mobs. They attack me and I can attack them as well.

**Comment by UltraNix** [comment] 2023-03-08 10:35
Fixed.

**Closed by UltraNix** 2023-03-08 10:35 UTC
Labels: PVP, Priority: Critical, Status: Confirmed
