### ISSUE TITLE
Twilight Portals , Bastion of Twilight

### ISSUE THREAD

**Issue by Tigroska** [gamefreedomgit/Maelstrom#3305] opened 2023-05-02 17:41 UTC
**Description:**
Bastion of Twilight , Vusial Bug with Twilight Portals , same thing i had in twlight realm on Teralion and Valiona so it makes boss hard to kill 
![WoWScrnShot_050223_201720](https://user-images.githubusercontent.com/125566782/235742117-4d297b9d-b586-4358-bc9a-2110a5253cab.jpg)

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Alandiel** [comment] 2023-05-02 18:02
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/3304

**Closed** 2023-05-02 18:03 UTC
