### ISSUE TITLE
PVP - Parry / dodge from behind

### ISSUE THREAD

**Issue by richysoscary** [gamefreedomgit/Maelstrom#2828] opened 2023-04-04 12:42 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
We dont need further explanation i think. Players can dodge / parry from behind, and they shouldnt.

My step kidney got parried on a >AFK< guy in BG.

This benefits other classes too, dont mark as rogue.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by richysoscary** [comment] 2023-04-04 12:59
![Garotte fail](https://user-images.githubusercontent.com/129841569/229799079-677fcd1e-a504-4c1f-bf5f-d2938cde663d.png)

@Waroxx-QA , Research done, garotte can be only casted from behind. it got parried.

**Comment by Renehadox** [comment] 2023-04-04 20:22
Why did you mark this as Research needed?

Attacks from behind shouldn't be dodged or parried.

Today a resto druid dodged me from behind :D

**Comment by Waroxx-QA** [comment] 2023-04-04 23:34
@Renehadox Research is needed about what is causing this, not about the validity of the issue.

**Comment by UltraNix** [comment] 2023-04-05 09:18
![WoWScrnShot_040523_111653](https://user-images.githubusercontent.com/80540499/230037895-3701f0bc-73be-49b9-9930-f872ce7dc39a.jpg)
![WoWScrnShot_040523_111655](https://user-images.githubusercontent.com/80540499/230037902-406ee118-04cb-4339-bd80-48b83808df2f.jpg)
![WoWScrnShot_040523_111657](https://user-images.githubusercontent.com/80540499/230037906-c12a7043-0a4d-488b-97ee-48332fe1d006.jpg)
Over 1k attacks - no single dodge/parry from behind.
So yeah - we need more info on this.

**Comment by richysoscary** [comment] 2023-04-05 09:24
@UltraNix I mean we should try it with geared characters, str, agi gives dodge/parry stats afaik.

**Comment by Renehadox** [comment] 2023-04-05 11:12
Expertise and Hit rating are bugged on this server.

I dodged / parried multiple times from behind on resto druids, resto shamans, even disc priests. 🗡️ 

Proof that i caught yesterday:

![Capture](https://user-images.githubusercontent.com/67479994/230063927-edb7dffa-a366-4a67-9ead-68bf4ff476ec.PNG)

Hammer of wrath misses Kyubi, a resto druid, and im over hit capped also i casted it when i was behind him, which is a bug.

My melee attack and my crusader strike were dodged from a feral druid from behind, which is a bug.

**Comment by UltraNix** [comment] 2023-04-06 11:01
@Renehadox @richysoscary Are you guys able to make a video with this bug?

**Comment by Renehadox** [comment] 2023-04-06 12:16
You mean we to make a bug of this video or show you a video of retail?

Like, combat log isn't enough for you?

I just dueled some random player, 2 hammer of wraths missed in a row.

There is definitely something a lot more bugged here...

Proof:
![miss02](https://user-images.githubusercontent.com/67479994/230376288-5c0f7eaf-3b62-4ff7-b133-95f22dd294cc.PNG)
![miss01](https://user-images.githubusercontent.com/67479994/230376299-fee32ab4-80b4-44ce-8774-c02aec3accb3.PNG)

I expect a fast fix for this bug....

**Comment by UltraNix** [comment] 2023-04-06 12:32
@Renehadox I need to know what is the cause. I don't need proofs from retail.
And this report is about parry/dodge from behind in PvP.

**Comment by Renehadox** [comment] 2023-04-06 12:53
> @Renehadox I need to know what is the cause. I don't need proofs from retail. And this report is about parry/dodge from behind in PvP.

Bro, think about it logically.

Aattacks made from behind, cannot be dodged or parried.

**Comment by dan-personal** [comment] 2023-04-10 21:31
@Renehadox 

You are being very hostile, and also very unhelpful. UltraNix needs more information in order to fix the bug. No-one is disputing that it is bugged. He wants to investigate the root cause and would like more information to do so. Treat the staff with a bit more respect.

**Comment by UltraNix** [comment] 2023-04-11 11:26
If you are able to replicate this bug in regular duel, just record a video of this.

**Comment by UltraNix** [comment] 2023-04-12 09:16
@Renehadox If you cannot help with this, then don't comment.

**Comment by Renehadox** [comment] 2023-04-12 10:38
> @Renehadox If you cannot help with this, then don't comment.

I am here to help and I'm helping, I have already reported a lot of bugs in a short period of time.

**Comment by UltraNix** [comment] 2023-04-25 16:12
@Renehadox @richysoscary Still happens (I mean parried/dodges attacks from behind in PvP)?

**Comment by UltraNix** [comment] 2023-06-17 11:05
No further info - closing.

**Closed by UltraNix** 2023-06-17 11:05 UTC
Labels: Core, Status: Need Info, Status: Confirmed, Priority: High
