### ISSUE TITLE
BM Hunter Killing streak

### ISSUE THREAD

**Issue by Sonni69** [gamefreedomgit/Maelstrom#4355] opened 2023-08-29 07:54 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Even when critting twice in a row with kill command, im not getting this buff. It used to work before patch 4.2, but i have paid attention to it for days now, analyzing recount data, and i havent gotten a single proc 

**How to reproduce:**
Spam kill command on target dummy untill you crit with it twice in a row, and witness that the talent did not proc.

**How it should work:**
If you land two consecutive crits with kill command, your 3rd one will have increased damage and reduced cost. 

**Database links:**
https://wowpedia.fandom.com/wiki/Killing_Streak

**Comment by Sketish** [comment] 2023-08-29 09:01
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4309

**Closed by Sketish** 2023-08-29 09:01 UTC
