### ISSUE TITLE
 i want report bug  Cataclysm Engineering  from this item [Electrostatic Condenser]

### ISSUE THREAD

**Issue by oooowwwweeee** [gamefreedomgit/Maelstrom#4939] opened 2023-11-03 12:08 UTC
Description:
i want report bug from this item [Electrostatic Condenser]
this item [Electrostatic Condenser] from Cataclysm Engineering  when i   while  herb or mining  or skinning must give me  occasionally collect Volatile Air 
but  this item  never work ! 

**How it should work:**
[Allows a skilled engineer to occasionally collect Volatile Air while mining, skinning, or collecting herbs.]

**Database links:**
https://cata-twinhead.twinstar.cz/?item=67494
https://www.wowhead.com/spell=95703/electrostatic-condenser

**Comment by Sketish** [comment] 2023-11-03 22:15
duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4929

**Closed by Sketish** 2023-11-03 22:15 UTC
