### ISSUE TITLE
[Hunter] Pet will not attack while sapped

### ISSUE THREAD

**Issue by djesic** [gamefreedomgit/Maelstrom#4727] opened 2023-10-09 07:52 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Rogue sapped me from stealth, but he was close enough for me to see him in stealth with Detect Hidden tracking.
I pressed pet attack on my pet action bar, but the pet didn't do anything.

**How to reproduce:**
Get sapped by rogue, issue pet attack command
Pet will not attack the target
Uncertain if different behavior in case rogue stays in stealth or cancels it.

**How it should work:**
Should be able to engage the target with pet.
Even if the target is in stealth but detected, as you share sight with pet.
Same goes for all classes with pet control (warlock, UH DK, frost mage)

**Comment by Sketish** [comment] 2023-10-10 07:07
Please provide any video

**Comment by djesic** [comment] 2023-10-10 07:22
Here's a retail forum post complaining about the balance of this: 
https://us.forums.blizzard.com/en/wow/t/can-we-get-pets-to-not-defend-flags/403482/3

This behavior has been the same since classic.

**Comment by Sketish** [comment] 2023-10-11 07:25
Need any cata video that people were doing this in bg

**Comment by djesic** [comment] 2023-10-11 08:21
Not finding hunter videos, again not really gameplay people put in their videos.
Is the reasoning not enough? I am CC'd, not my pet - why would pet be unable to perform its abilities?

**Comment by djesic** [comment] 2023-10-11 08:26
Here is another forum post from 2009 
https://www.mmo-champion.com/threads/660285-Sap-capping?p=6710232&viewfull=1#post6710232

> Re: Sap capping...
Pet Classes can deal with this. Warlocks, Hunters, and Unholy Death Knights can use their pets to interrupt the cap.

**Comment by Crusaderz** [comment] 2023-10-11 17:44
It's a known fact, players can control their pets despite being in CC and it's worked that way since 2006

**Comment by Crusaderz** [comment] 2023-10-11 17:54
Here's zumio sending his monkey to attack a rogue while under Blind, the pet is in passive mode

https://youtu.be/_Csv-0VZWDo?t=741

**Comment by djesic** [comment] 2023-10-12 07:26
@Sketish is that enough proof?

**Comment by UltraNix** [comment] 2023-10-13 13:18
Just tested and everything works okay. Being sapped, I'm able to command the pet to attack rogue.

**Comment by UltraNix** [comment] 2023-10-13 13:20
Yep.

**Comment by djesic** [comment] 2023-10-13 13:21
I'm not sure then.

I opened this ticket because I was in AB on LM and a rogue sapped me and was walking around and I could not send pet to attack him while I saw him.

**Comment by UltraNix** [comment] 2023-10-13 13:24
That's why pleasw record it as I can't reproduce it. Otherwise, I will close this one. What error appeared on your screen? Maybe rogue was already gone when you commanded pet to attack?

**Comment by djesic** [comment] 2023-10-13 13:26
Pet just didn't budge. No circle around the target animation that usually plays when pet starts attacking a target. No error appeared. Pet was not CC'd. Just standing there like a lemon

**Comment by djesic** [comment] 2023-10-13 20:47
Ok, failed to reproduce in a duel. Will close this ticket but update if I encounter it again

**Comment by Crusaderz** [comment] 2023-10-14 23:25
@djesic 
Try to make the rogue first use distract on your pet and then sap on you, will the pet obey your commands in this case?

**Comment by djesic** [comment] 2023-10-15 10:37
> @djesic Try to make the rogue first use distract on your pet and then sap on you, will the pet obey your commands in this case?

Good suggestion, I'll give it a try.

I was in a similar scenario yesterday as the initial report, and while I could issue the attack command, my pet did not cast Dash when running for the target. I was not able to reproduce this in a duel though

**Comment by djesic** [comment] 2023-10-15 13:31
@UltraNix 
Ok, happened again in BG
I was mounted and then sapped, dismounted while sapped and pet would not start attack

**Comment by djesic** [comment] 2023-10-15 13:33
Once sapped while I was dismounted, I was able to send my pet, but it didn't cast Dash when starting to go towards it, even though it was on autocast

**Comment by UltraNix** [comment] 2023-10-16 06:40
@djesic Video or some screenshots would be helpful.

**Closed** 2023-11-15 09:14 UTC
Labels: Class: Hunter, Pet, Status: Need Info, Priority: Medium
