### ISSUE TITLE
[Rogue] Combo points putting me in combat

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2343] opened 2023-03-05 22:23 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
in BG something keeps putting me in combat, could be Honor Among Thieves talent?
https://gyazo.com/bdcfeb7f259703b7efdef365a05c4964
this is my talent spec (just a levelling build)
I'm just using full starter gear no weird trinkets or weapons

Here is a clip of it happening:
https://www.youtube.com/watch?v=Kkuvb8cGNfI&feature=youtu.be

You can see me not attacking, not being attacked just chilling in stealth. I stay in combat after vanish which can happen occasionally, then I leave combat for about half a sec and re-enter it?? 

This is happening like every bg and I think it might be Honor among thieves but haven't tested

**Comment by sassouiabd** [comment] 2023-03-06 00:20
Its this: 
https://github.com/gamefreedomgit/Maelstrom/issues/2341

**Comment by SimonBpvp** [comment] 2023-03-06 00:58
I believe anything which generates combo points as a rogue will put you in combat.

This means Premeditation and Honor Among Thieves will incorrectly put you into combat.

Premed tested on a training dummy right now confirmed entering combat.

**Comment by SimonBpvp** [comment] 2023-03-06 01:00
> Its this: #2341

I think that report is wrong, its not just about targetting, its from Honor Among Thieves imo.

**Comment by sassouiabd** [comment] 2023-03-06 13:30
Yeah this issue should be flagged duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/2341 i have updated mine

**Comment by UltraNix** [comment] 2023-03-10 17:40
Fixed.

**Closed by UltraNix** 2023-03-10 17:40 UTC
Labels: Class: Rogue, Spell, Priority: High, Status: Needs Confirmation
