### ISSUE TITLE
Mage procs without hitting

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#2300] opened 2023-03-02 15:37 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
im getting impact procs from using flamestrike without hitting any targets

**How to reproduce:**
just hit air with your flame strike

**How it should work:**
procs come from different things but never from just hitting air or whiffing your spell

**Database links:**

**Comment by MullichWhitemane** [comment] 2023-03-02 22:32
This is a duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/2103 so I'll close this and merge.

**Closed** 2023-03-02 22:33 UTC
