### ISSUE TITLE
Hyjal Daily Supplies for the Other Side bugged.

### ISSUE THREAD

**Issue by BrotherWolf7** [gamefreedomgit/Maelstrom#4173] opened 2023-08-12 14:41 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

Cannot loot the blueroot vine for the daily quest "Supplies for the Other Side."

**How to reproduce:**

Attempt to loot the vines. 

**How it should work:**

Vines should be lootable.

**Database links:**

**Comment by Sketish** [comment] 2023-08-12 15:18
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4169

**Closed by Sketish** 2023-08-12 15:18 UTC
