### ISSUE TITLE
[paladin] seals and proc rate Gurthalak,_Voice_of_the_Deeps

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#5548] opened 2024-01-20 23:58 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
seal of truth affects the chance of triggering https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps

**How to reproduce:**
to attack with on seal, with https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps

**How it should work:**
seals should not affects the chance of triggering https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps

**Database links:**
https://wowpedia.fandom.com/wiki/Seal_of_Truth
https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps

**Comment by doctopo** [comment] 2024-01-21 00:18
What you mean seal ,i tried to keep dot on dummy and it was not procing it

**Comment by mipanka** [comment] 2024-01-21 00:26
"Fills you with Holy Light, causing melee attacks to deal 13% additional Holy damage and apply Censure to the target."
from https://wowpedia.fandom.com/wiki/Seal_of_Truth

**Comment by Jcbn0** [comment] 2024-01-21 01:26
Rets are doomed

**Comment by bonfax4** [comment] 2024-01-21 04:15
In case proof is needed, if this post is accurate ( did not test ) : https://www.bluetracker.gg/wow/topic/us-en/3811455871-gurth-far-more-broken-in-pvp-pve-than-dwtr/

**Comment by Renehadox** [comment] 2024-01-21 04:54
> **Description:** seal of truth affects the chance of triggering https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps
> 
> **How to reproduce:** to attack with on seal, with https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps
> 
> **How it should work:** seals should not affects the chance of triggering https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps
> 
> **Database links:** https://wowpedia.fandom.com/wiki/Seal_of_Truth https://wowpedia.fandom.com/wiki/Gurthalak,_Voice_of_the_Deeps

how do you know this when you play a mage?

**Comment by Pornoodemon** [comment] 2024-01-21 12:52
> how do you know this when you play a mage?

He plays all classes х)

**Comment by Renehadox** [comment] 2024-01-24 02:36
I reported this bug also it got removed as a non bug and this report is marked as valid?

**Comment by UltraNix** [comment] 2024-01-24 13:49
Just tested and see no additional procs from Seal of Truth.
About 

> In case proof is needed, if this post is accurate ( did not test ) : https://www.bluetracker.gg/wow/topic/us-en/3811455871-gurth-far-more-broken-in-pvp-pve-than-dwtr/
> 
> https://www.mmo-champion.com/content/2613-Patch-4-3-Hotfixes-January-9
> 
> > [Souldrinker](http://db.mmo-champion.com/i/78488/souldrinker/) and [Gurthalak, Voice of the Deeps](http://db.mmo-champion.com/i/78487/gurthalak-voice-of-the-deeps/) no longer have a chance to proc twice for paladins with Seal of Truth active.

We can see there info about twice proccing from Seal of Truth - every application of Censure and Seal of Truth weapon damage with 5 stacks of Censure. That has been fixed, so Censure no longer procs it - which is the case on our server.

Seal of Truth (when you have 5 stacks on Censure) can procs Gurthalak and this is not a bug.

**Comment by UltraNix** [comment] 2024-01-24 13:56
Hmm, I don't understand that. Blizzard says:
`[Souldrinker](http://db.mmo-champion.com/i/78488/souldrinker/) and [Gurthalak, Voice of the Deeps](http://db.mmo-champion.com/i/78487/gurthalak-voice-of-the-deeps/) no longer have a chance to proc twice for paladins with Seal of Truth active.`
What was the twice procs here? Only when you have 5 stacks of Censure, there is additional weapon dmg - that one procs now Gurthalak. But only this. So where is the that second proc from that Seal?

**Comment by UltraNix** [comment] 2024-01-24 14:00
According to https://www.bluetracker.gg/wow/topic/us-en/3811455871-gurth-far-more-broken-in-pvp-pve-than-dwtr/#372
`Retribution was getting more than twice as many proc chances than we intended. This was caused by the application of Censure, not the dot itself ticking.`
Censure application does not procs Gurthalak. If so (and SoT still can procs when you have 5 stacks of Censure applied on your victim) - there is no bug here.

**Comment by bonfax4** [comment] 2024-01-24 14:06
No. They specifically removed that interaction. And whatt caused it was censure debuff counted as a melee hit, this was a bug from wotlk with certain icc items. Seal hits never procced it. The twice there means every auto was rolling twice because of the censure refresh. Also the seal should do dmg while stacking up too, not just at max stacks, despite the tooltip not being clear about it.

**Comment by bonfax4** [comment] 2024-01-24 14:13
@Ultranix

**Comment by bonfax4** [comment] 2024-01-24 14:16
Also is SOT dmg is currently proccing it, what about seal of command cleave ?

**Comment by UltraNix** [comment] 2024-01-24 14:40
Tested Seals of Command with Seal of Truth - 2 procs: one from melee, one from Seal of Truth trigger (5 stacks of Censure).

**Comment by bonfax4** [comment] 2024-01-24 14:42
How do you test this ? You set gurth proc to 100% ?

**Comment by UltraNix** [comment] 2024-01-24 15:00
Yes - for testing.

**Comment by bonfax4** [comment] 2024-01-24 15:10
I can see ppl QQ'ing in forums that the dmg dropped by half. If hit + sot + censure application all had a chance to proc on retail before the hotfix, the dmg would not drop by that much right ?  Nobody ever mentions the proc triple dipping either

**Comment by bonfax4** [comment] 2024-01-24 15:15
Also I guess you were correct, SoT dmg might have been what was proccing the weapon, and not censure itself. Gm might have misspoke but the official changelog does say SoT.

**Comment by Renehadox** [comment] 2024-01-24 15:21
I dueled a ret paladin 2 weeks ago with gurth weapon and 4 tentacles spawned in 3 seconds, i made a bug report about proc chacne devs said its working as intended.

So that 2% proc chance of spawning 4 tentacles is a rng ?

**Comment by bonfax4** [comment] 2024-01-24 15:31
@ultranix Also before touching, this ppl on the forums mentioned that landslide proc chance wasn't altered with the nerf. And it was never clear if SoT actually increased the uptime or not or if the nerf was specifically applied to gurth to not proc from it. Just saying this on case the fix may nerf rets further if not properly investigated.

**Comment by UltraNix** [comment] 2024-01-24 15:36
I'm confused right now with this one :)

**Comment by bonfax4** [comment] 2024-01-24 15:43
https://www.mmo-champion.com/threads/1058589-Ret-Gurthalak-nerf/page10 read this forum I guess.

**Comment by mipanka** [comment] 2024-01-24 15:48
I wrote about seal, in my second post here(with link), where direct dmg from seal, give chance of trigger proc gurth. As know, only hit melee attack should trigger proc, all dmg, proc all seals, should not of trigger proc gurth.

**Comment by mipanka** [comment] 2024-01-24 15:51
This bug was on few pservers, later I'll find more proof, but I found out from wowhead comment. Idk they was deleted or no.

**Comment by bonfax4** [comment] 2024-01-24 15:56
> This bug was on few pservers, later I'll find more proof, but I found out from wowhead comment. Idk they was deleted or no.

The problem is figuring out if removing the possibility of seal of truth to proc mellee related stuff is the way to go or if they should just make a change to the weapon to not proc from it I guess. Because that nerf goes beyond gurth if that's the case. Exorcism procs sot which could proc other mellee stuff for example like enchants/trinkets from what I'm understanding reading that post.

**Comment by bonfax4** [comment] 2024-01-24 16:01
> https://www.mmo-champion.com/threads/1121605-Paladins-and-Gurthalak-Voice-of-the-Deeps
> 
> I guess there is no bug, it works as intended.

No.. gurth got nerfed...

**Comment by UltraNix** [comment] 2024-01-24 16:16
If we remove proc from Sot, then about other classes with abilities to proc from melee attacks, e.g. shaman's windfury?

**Comment by mipanka** [comment] 2024-01-24 16:27
> If we remove proc from Sot, then about other classes with abilities to proc from melee attacks, e.g. shaman's windfury?

Idk about sham, but know about warrior mastery, and mastery arms warrior should trigger proc gurth

**Comment by doctopo** [comment] 2024-01-24 16:30
The reason why it got nerfed seem beceause Blizzard is an ass and want ret to be bottom dps ,they litelerally told it ,so they made SOT damage not considered as melee hit which fucked landslide procs i guess or something like that?

**Comment by bonfax4** [comment] 2024-01-26 21:53
> If we remove proc from Sot, then about other classes with abilities to proc from melee attacks, e.g. shaman's windfury?

Shaman windfury was already researched back in retail and it didn't proc no kaled

**Comment by UltraNix** [comment] 2024-01-31 20:44
Fixed.

**Closed by UltraNix** 2024-01-31 20:44 UTC
Labels: Class: Paladin, Item, Priority: High
