### ISSUE TITLE
QuestID: 29009 - Candy Bucket is not clickable (Stonetalon Mountains, Krom'gar Fortress)

### ISSUE THREAD

**Issue by Humanbasher** [gamefreedomgit/Maelstrom#6236] opened 2024-10-20 17:49 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
QuestID: 29009 - Candy Bucket is not clickable (Stonetalon Mountains, Krom'gar Fortress)

**How to reproduce:**
Stand in front of the Candy Bucket in Stonetalon Mountains, Krom'gar Fortress

**How it should work:**
Klick, collect the quest reward "Handful of Treats".

**Database links:**
https://www.wowhead.com/cata/quest=29009/candy-bucket
https://www.wowhead.com/cata/item=37586/handful-of-treats

**Comment by Sketish** [comment] 2024-10-21 07:23
duplicate of 
https://github.com/gamefreedomgit/Maelstrom/issues/6236

**Closed by Sketish** 2024-10-21 07:23 UTC
Labels: Priority: High, Quest, GameEvent

**Comment by Humanbasher** [comment] 2024-10-21 10:12
There is no duplicate? Linking on my on ticket?

Am Mo., 21. Okt. 2024 um 09:23 Uhr schrieb Sketish ***@***.***

**Comment by Sketish** [comment] 2024-10-21 14:33
https://github.com/gamefreedomgit/Maelstrom/issues/6234 this one, my bad
