### ISSUE TITLE
spellsteal breaks sap

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#4155] opened 2023-08-11 02:07 UTC
**Description:**
spellsteal is breaking sap

if you spellsteal a target that is sapped the sap will instantly break

**Comment by Sketish** [comment] 2023-08-11 07:59
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/4091

**Closed by Sketish** 2023-08-11 07:59 UTC
