### ISSUE TITLE
Assasinate Creed not working properlly (Flying)

### ISSUE THREAD

**Issue by Skurten** [gamefreedomgit/Maelstrom#5275] opened 2023-12-21 10:39 UTC
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/quest=30093/assassinate-creed
[//]: # (cata-twinhead.twinstar.cz) https://cata-twinhead.twinstar.cz/?quest=30093

**Description:**
Not getting teleported out while flying over

**How to reproduce:**
no clue

**How it should work:**
And i do not think its intended that you could just fly in there and kill Lord hiram creed

**Database links:**
https://www.wowhead.com/quest=30093/assassinate-creed
![bugreport2](https://github.com/gamefreedomgit/Maelstrom/assets/146117505/c5931993-2193-420a-88a5-0fea0160ccbc)

**Comment by Sketish** [comment] 2023-12-21 16:32
Duplicate of https://github.com/gamefreedomgit/Maelstrom/issues/5274

**Closed by Sketish** 2023-12-21 16:32 UTC
